package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.Ctr;

public interface CtrMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    int deleteByPrimaryKey(Integer sqlId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    int insert(Ctr record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    int insertSelective(Ctr record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    Ctr selectByPrimaryKey(Integer sqlId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    int updateByPrimaryKeySelective(Ctr record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    int updateByPrimaryKey(Ctr record);
}