package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TAccesoHis;

public interface TAccesoHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    int deleteByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    int insert(TAccesoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    int insertSelective(TAccesoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    TAccesoHis selectByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    int updateByPrimaryKeySelective(TAccesoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acceso_his
     *
     * @mbg.generated Fri May 14 12:43:21 CEST 2021
     */
    int updateByPrimaryKey(TAccesoHis record);
}