package com.dina.genasoft.db.mapper;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TAcceso;

public interface TAccesoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int deleteByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int insert(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int insertSelective(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    TAcceso selectByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int updateByPrimaryKeySelective(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int updateByPrimaryKey(TAcceso record);

    /**
     * Obtenemos el acceso del empleado
     * @param empleado El empleado que ha realizado el acceso o que lo solicita.
     * @return El acceso si existe.
     */
    TAcceso obtenerAccesoEmpleado(@Param("empleado") Integer idEmpleado);

    /**
     * Eliminamos el acceso del empleado
     * @param empleado El empleado que ha realizado el acceso o que lo solicita.
     * @return Los accesos eliminados
     */
    int eliminarAccesoEmpleado(@Param("empleado") Integer idEmpleado);
}