package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TAcceso;

public interface TAccesoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    int deleteByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    int insert(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    int insertSelective(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    TAcceso selectByPrimaryKey(Integer idAcceso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    int updateByPrimaryKeySelective(TAcceso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    int updateByPrimaryKey(TAcceso record);
}