package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TCentros;

public interface TCentrosMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int insert(TCentros record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int insertSelective(TCentros record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    TCentros selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int updateByPrimaryKeySelective(TCentros record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_centros
     * @mbg.generated  Tue Feb 16 11:44:14 CET 2021
     */
    int updateByPrimaryKey(TCentros record);
}