package com.dina.genasoft.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TComprasFict;

public interface TComprasFictMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int insert(TComprasFict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int insertSelective(TComprasFict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    TComprasFict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int updateByPrimaryKeySelective(TComprasFict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int updateByPrimaryKey(TComprasFict record);

    /**
     * Método para crear la compra y obtener el ID del registro creado.
     * @param map Los datos de la compra a crear.
     */
    void insertRecord(Map<String, Object> map);

    List<TComprasFict> obtenerComprasAlbaranesLotesPartidas(@Param("list") List<String> lAlbaranes, @Param("list2") List<String> lLotes, @Param("list3") List<String> lPartidas);

    List<String> obtenerNumerosAlbaranCompras();

    List<String> obtenerLotesCompras();

    List<String> obtenerPartidasCompras();

    List<TComprasFict> obtenerComprasIds(@Param("list") List<Integer> ids);
}