package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TComprasFictHis;

public interface TComprasFictHisMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int insert(TComprasFictHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int insertSelective(TComprasFictHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    TComprasFictHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int updateByPrimaryKeySelective(TComprasFictHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_compras_fict_his
     * @mbg.generated  Sun Nov 07 18:44:05 CET 2021
     */
    int updateByPrimaryKey(TComprasFictHis record);
}