package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TControlProductoTerminadoHis;

public interface TControlProductoTerminadoHisMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    int insert(TControlProductoTerminadoHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    int insertSelective(TControlProductoTerminadoHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    TControlProductoTerminadoHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    int updateByPrimaryKeySelective(TControlProductoTerminadoHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_his
     * @mbg.generated  Wed May 26 19:42:13 CEST 2021
     */
    int updateByPrimaryKey(TControlProductoTerminadoHis record);
}