package com.dina.genasoft.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TControlProductoTerminadoFotos;

public interface TControlProductoTerminadoFotosMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    int insert(TControlProductoTerminadoFotos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    int insertSelective(TControlProductoTerminadoFotos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    TControlProductoTerminadoFotos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    int updateByPrimaryKeySelective(TControlProductoTerminadoFotos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_control_producto_terminado_fotos
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    int updateByPrimaryKey(TControlProductoTerminadoFotos record);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdControlPt(@Param("idControlPt") Integer idControlPt);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdLinea(@Param("idLinea") Integer idControlPt);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdControlPtDescripcion(@Param("idControlPt") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdLineaDescripcion(@Param("idLinea") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto);

    TControlProductoTerminadoFotos obtenerImagenIdControlPtDescripcionOrden(@Param("idControlPt") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto, @Param("orden") Integer orden);

    TControlProductoTerminadoFotos obtenerImagenIdLineaDescripcionOrden(@Param("idLinea") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto, @Param("orden") Integer orden);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdControlPtDescripcionLike(@Param("idControlPt") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto);

    List<TControlProductoTerminadoFotos> obtenerImagenesIdLineaDescripcionLike(@Param("idLinea") Integer idControlPt, @Param("descripcionFoto") String descripcionFoto);
}