package com.dina.genasoft.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TDiametrosProducto;

public interface TDiametrosProductoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    int insert(TDiametrosProducto record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    int insertSelective(TDiametrosProducto record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    TDiametrosProducto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    int updateByPrimaryKeySelective(TDiametrosProducto record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    int updateByPrimaryKey(TDiametrosProducto record);

    List<TDiametrosProducto> obtenerTodosDiametros();

    List<TDiametrosProducto> obtenerDiametrosProducto(@Param("idProducto") Integer idProducto);
}