package com.dina.genasoft.db.mapper;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TLineasVentas;
import com.dina.genasoft.db.entity.TLineasVentasHis;

public interface TLineasVentasHisMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    int insert(TLineasVentasHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    int insertSelective(TLineasVentasHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    TLineasVentasHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    int updateByPrimaryKeySelective(TLineasVentasHis record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_lineas_ventas_his
     * @mbg.generated  Thu Dec 09 13:54:01 CET 2021
     */
    int updateByPrimaryKey(TLineasVentasHis record);

    int crearLineaVentaHis(TLineasVentas record);

    int modificarLineaVentaHis(TLineasVentas record);

    TLineasVentasHis obtenerLineaVentaHisPorIdExterno(@Param("idExterno") Double idExterno);
}