package com.dina.genasoft.db.mapper;

import com.dina.genasoft.db.entity.TPais;

public interface TPaisMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    int deleteByPrimaryKey(String codigo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    int insert(TPais record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    int insertSelective(TPais record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    TPais selectByPrimaryKey(String codigo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    int updateByPrimaryKeySelective(TPais record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_pais
     * @mbg.generated  Mon Jun 03 18:39:23 CEST 2024
     */
    int updateByPrimaryKey(TPais record);
}