package com.dina.genasoft.db.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.dina.genasoft.db.entity.TProductos;

public interface TProductosMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    int insert(TProductos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    int insertSelective(TProductos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    TProductos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    int updateByPrimaryKeySelective(TProductos record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    int updateByPrimaryKey(TProductos record);

    /**
     * Método para crear el producto y obtener el ID del registro creado.
     * @param map Los datos del producto a crear.
     */
    public void insertRecord(Map<String, Object> map);

    TProductos obtenerProductoPorNombre(@Param("nombre") String nombre);

    List<TProductos> obtenerTodosProductos();

    List<TProductos> obtenerProductosActivos();
}