package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class Art implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Integer sqlId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date sqlModTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ref;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String obs;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artPla;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double pso;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.lrg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double lrg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.anc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double anc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.alt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double alt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.vol
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double vol;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short plt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.com_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short comCal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.se_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short seVta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.es_cmp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short esCmp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.es_rtr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short esRtr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long mrc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pre_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String preTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.fam
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String fam;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.dsc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String dsc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.var_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long varArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long catArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.org_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long orgArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.ctf_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ctfPrd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short cfc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String gtin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String gtinDc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.dsc_nom
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String dscNom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long altUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date altTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long modUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date modTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short off;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long offUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date offTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double cst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cst_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String cstTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String nameAbr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.plt_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String pltTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.und_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String undCom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.fct_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double fctCom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.art_pre_tip_val
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String artPreTipVal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cst_div
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double cstDiv;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pso_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoCst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pso_cst_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short psoCstMod;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pso_cst_man
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoCstMan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.lote_on
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short loteOn;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pre_cos
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double preCos;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.sbv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short sbv;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.tox
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short tox;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.epi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short epi;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.prv_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long prvEntTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.prv_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long prvEnt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.alq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short alq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pre_alq_fi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double preAlqFi;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.reg_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String regNro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.reg_eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String regEje;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.tox_niv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String toxNiv;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.soivre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long soivre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.adr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short adr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.eqv_alm
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long eqvAlm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cst_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double cstGen;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cod_onu
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long codOnu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cat_tpt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long catTpt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cos_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cosGrp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mp_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String mpId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mp_name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String mpName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.cod_cpt_opf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long codCptOpf;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.b_no_stk
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short bNoStk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.ref_ant
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String refAnt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.emb_cls
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long embCls;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.mp_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String mpRef;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column art.pso_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoEnt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.sql_id
     * @return  the value of art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Integer getSqlId() {
        return sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.sql_id
     * @param sqlId  the value for art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlId(Integer sqlId) {
        this.sqlId = sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.sql_mod_tim
     * @return  the value of art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getSqlModTim() {
        return sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.sql_mod_tim
     * @param sqlModTim  the value for art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlModTim(Date sqlModTim) {
        this.sqlModTim = sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.id
     * @return  the value of art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.id
     * @param id  the value for art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.ref
     * @return  the value of art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.ref
     * @param ref  the value for art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.name
     * @return  the value of art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.name
     * @param name  the value for art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.obs
     * @return  the value of art.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getObs() {
        return obs;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.obs
     * @param obs  the value for art.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setObs(String obs) {
        this.obs = obs;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.art_pla
     * @return  the value of art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtPla() {
        return artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.art_pla
     * @param artPla  the value for art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtPla(Long artPla) {
        this.artPla = artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pso
     * @return  the value of art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPso() {
        return pso;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pso
     * @param pso  the value for art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPso(Double pso) {
        this.pso = pso;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.lrg
     * @return  the value of art.lrg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getLrg() {
        return lrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.lrg
     * @param lrg  the value for art.lrg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setLrg(Double lrg) {
        this.lrg = lrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.anc
     * @return  the value of art.anc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getAnc() {
        return anc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.anc
     * @param anc  the value for art.anc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAnc(Double anc) {
        this.anc = anc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.alt
     * @return  the value of art.alt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.alt
     * @param alt  the value for art.alt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAlt(Double alt) {
        this.alt = alt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.vol
     * @return  the value of art.vol
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.vol
     * @param vol  the value for art.vol
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setVol(Double vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.plt
     * @return  the value of art.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getPlt() {
        return plt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.plt
     * @param plt  the value for art.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPlt(Short plt) {
        this.plt = plt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.com_cal
     * @return  the value of art.com_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getComCal() {
        return comCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.com_cal
     * @param comCal  the value for art.com_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setComCal(Short comCal) {
        this.comCal = comCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.se_vta
     * @return  the value of art.se_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getSeVta() {
        return seVta;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.se_vta
     * @param seVta  the value for art.se_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSeVta(Short seVta) {
        this.seVta = seVta;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.es_cmp
     * @return  the value of art.es_cmp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getEsCmp() {
        return esCmp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.es_cmp
     * @param esCmp  the value for art.es_cmp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEsCmp(Short esCmp) {
        this.esCmp = esCmp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.es_rtr
     * @return  the value of art.es_rtr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getEsRtr() {
        return esRtr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.es_rtr
     * @param esRtr  the value for art.es_rtr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEsRtr(Short esRtr) {
        this.esRtr = esRtr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mrc
     * @return  the value of art.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getMrc() {
        return mrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mrc
     * @param mrc  the value for art.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMrc(Long mrc) {
        this.mrc = mrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pre_tip
     * @return  the value of art.pre_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getPreTip() {
        return preTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pre_tip
     * @param preTip  the value for art.pre_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPreTip(String preTip) {
        this.preTip = preTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.fam
     * @return  the value of art.fam
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getFam() {
        return fam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.fam
     * @param fam  the value for art.fam
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setFam(String fam) {
        this.fam = fam;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.dsc
     * @return  the value of art.dsc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.dsc
     * @param dsc  the value for art.dsc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setDsc(String dsc) {
        this.dsc = dsc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.var_art
     * @return  the value of art.var_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getVarArt() {
        return varArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.var_art
     * @param varArt  the value for art.var_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setVarArt(Long varArt) {
        this.varArt = varArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cat_art
     * @return  the value of art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCatArt() {
        return catArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cat_art
     * @param catArt  the value for art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCatArt(Long catArt) {
        this.catArt = catArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.org_art
     * @return  the value of art.org_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getOrgArt() {
        return orgArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.org_art
     * @param orgArt  the value for art.org_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOrgArt(Long orgArt) {
        this.orgArt = orgArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.ctf_prd
     * @return  the value of art.ctf_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCtfPrd() {
        return ctfPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.ctf_prd
     * @param ctfPrd  the value for art.ctf_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCtfPrd(String ctfPrd) {
        this.ctfPrd = ctfPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cfc
     * @return  the value of art.cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getCfc() {
        return cfc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cfc
     * @param cfc  the value for art.cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfc(Short cfc) {
        this.cfc = cfc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.gtin
     * @return  the value of art.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getGtin() {
        return gtin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.gtin
     * @param gtin  the value for art.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setGtin(String gtin) {
        this.gtin = gtin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.gtin_dc
     * @return  the value of art.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getGtinDc() {
        return gtinDc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.gtin_dc
     * @param gtinDc  the value for art.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setGtinDc(String gtinDc) {
        this.gtinDc = gtinDc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.dsc_nom
     * @return  the value of art.dsc_nom
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getDscNom() {
        return dscNom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.dsc_nom
     * @param dscNom  the value for art.dsc_nom
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setDscNom(String dscNom) {
        this.dscNom = dscNom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.alt_usr
     * @return  the value of art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getAltUsr() {
        return altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.alt_usr
     * @param altUsr  the value for art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltUsr(Long altUsr) {
        this.altUsr = altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.alt_tim
     * @return  the value of art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getAltTim() {
        return altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.alt_tim
     * @param altTim  the value for art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltTim(Date altTim) {
        this.altTim = altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mod_usr
     * @return  the value of art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getModUsr() {
        return modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mod_usr
     * @param modUsr  the value for art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModUsr(Long modUsr) {
        this.modUsr = modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mod_tim
     * @return  the value of art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getModTim() {
        return modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mod_tim
     * @param modTim  the value for art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModTim(Date modTim) {
        this.modTim = modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.off
     * @return  the value of art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getOff() {
        return off;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.off
     * @param off  the value for art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOff(Short off) {
        this.off = off;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.off_usr
     * @return  the value of art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getOffUsr() {
        return offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.off_usr
     * @param offUsr  the value for art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffUsr(Long offUsr) {
        this.offUsr = offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.off_tim
     * @return  the value of art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getOffTim() {
        return offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.off_tim
     * @param offTim  the value for art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffTim(Date offTim) {
        this.offTim = offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cst
     * @return  the value of art.cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getCst() {
        return cst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cst
     * @param cst  the value for art.cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCst(Double cst) {
        this.cst = cst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cst_tip
     * @return  the value of art.cst_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCstTip() {
        return cstTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cst_tip
     * @param cstTip  the value for art.cst_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCstTip(String cstTip) {
        this.cstTip = cstTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.name_abr
     * @return  the value of art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getNameAbr() {
        return nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.name_abr
     * @param nameAbr  the value for art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setNameAbr(String nameAbr) {
        this.nameAbr = nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.plt_tip
     * @return  the value of art.plt_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getPltTip() {
        return pltTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.plt_tip
     * @param pltTip  the value for art.plt_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPltTip(String pltTip) {
        this.pltTip = pltTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.und_com
     * @return  the value of art.und_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getUndCom() {
        return undCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.und_com
     * @param undCom  the value for art.und_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setUndCom(String undCom) {
        this.undCom = undCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.fct_com
     * @return  the value of art.fct_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getFctCom() {
        return fctCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.fct_com
     * @param fctCom  the value for art.fct_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setFctCom(Double fctCom) {
        this.fctCom = fctCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.art_pre_tip_val
     * @return  the value of art.art_pre_tip_val
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getArtPreTipVal() {
        return artPreTipVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.art_pre_tip_val
     * @param artPreTipVal  the value for art.art_pre_tip_val
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtPreTipVal(String artPreTipVal) {
        this.artPreTipVal = artPreTipVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cst_div
     * @return  the value of art.cst_div
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getCstDiv() {
        return cstDiv;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cst_div
     * @param cstDiv  the value for art.cst_div
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCstDiv(Double cstDiv) {
        this.cstDiv = cstDiv;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pso_cst
     * @return  the value of art.pso_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoCst() {
        return psoCst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pso_cst
     * @param psoCst  the value for art.pso_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoCst(Double psoCst) {
        this.psoCst = psoCst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pso_cst_mod
     * @return  the value of art.pso_cst_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getPsoCstMod() {
        return psoCstMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pso_cst_mod
     * @param psoCstMod  the value for art.pso_cst_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoCstMod(Short psoCstMod) {
        this.psoCstMod = psoCstMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pso_cst_man
     * @return  the value of art.pso_cst_man
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoCstMan() {
        return psoCstMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pso_cst_man
     * @param psoCstMan  the value for art.pso_cst_man
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoCstMan(Double psoCstMan) {
        this.psoCstMan = psoCstMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.lote_on
     * @return  the value of art.lote_on
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getLoteOn() {
        return loteOn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.lote_on
     * @param loteOn  the value for art.lote_on
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setLoteOn(Short loteOn) {
        this.loteOn = loteOn;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pre_cos
     * @return  the value of art.pre_cos
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPreCos() {
        return preCos;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pre_cos
     * @param preCos  the value for art.pre_cos
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPreCos(Double preCos) {
        this.preCos = preCos;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.sbv
     * @return  the value of art.sbv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getSbv() {
        return sbv;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.sbv
     * @param sbv  the value for art.sbv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSbv(Short sbv) {
        this.sbv = sbv;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.tox
     * @return  the value of art.tox
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getTox() {
        return tox;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.tox
     * @param tox  the value for art.tox
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setTox(Short tox) {
        this.tox = tox;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.epi
     * @return  the value of art.epi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getEpi() {
        return epi;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.epi
     * @param epi  the value for art.epi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEpi(Short epi) {
        this.epi = epi;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.prv_ent_tip
     * @return  the value of art.prv_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPrvEntTip() {
        return prvEntTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.prv_ent_tip
     * @param prvEntTip  the value for art.prv_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrvEntTip(Long prvEntTip) {
        this.prvEntTip = prvEntTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.prv_ent
     * @return  the value of art.prv_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPrvEnt() {
        return prvEnt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.prv_ent
     * @param prvEnt  the value for art.prv_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrvEnt(Long prvEnt) {
        this.prvEnt = prvEnt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.alq
     * @return  the value of art.alq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getAlq() {
        return alq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.alq
     * @param alq  the value for art.alq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAlq(Short alq) {
        this.alq = alq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pre_alq_fi
     * @return  the value of art.pre_alq_fi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPreAlqFi() {
        return preAlqFi;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pre_alq_fi
     * @param preAlqFi  the value for art.pre_alq_fi
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPreAlqFi(Double preAlqFi) {
        this.preAlqFi = preAlqFi;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.reg_nro
     * @return  the value of art.reg_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRegNro() {
        return regNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.reg_nro
     * @param regNro  the value for art.reg_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRegNro(String regNro) {
        this.regNro = regNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.reg_eje
     * @return  the value of art.reg_eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRegEje() {
        return regEje;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.reg_eje
     * @param regEje  the value for art.reg_eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRegEje(String regEje) {
        this.regEje = regEje;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.tox_niv
     * @return  the value of art.tox_niv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getToxNiv() {
        return toxNiv;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.tox_niv
     * @param toxNiv  the value for art.tox_niv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setToxNiv(String toxNiv) {
        this.toxNiv = toxNiv;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.soivre
     * @return  the value of art.soivre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getSoivre() {
        return soivre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.soivre
     * @param soivre  the value for art.soivre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSoivre(Long soivre) {
        this.soivre = soivre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.adr
     * @return  the value of art.adr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getAdr() {
        return adr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.adr
     * @param adr  the value for art.adr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAdr(Short adr) {
        this.adr = adr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.eqv_alm
     * @return  the value of art.eqv_alm
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEqvAlm() {
        return eqvAlm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.eqv_alm
     * @param eqvAlm  the value for art.eqv_alm
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEqvAlm(Long eqvAlm) {
        this.eqvAlm = eqvAlm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cst_gen
     * @return  the value of art.cst_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getCstGen() {
        return cstGen;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cst_gen
     * @param cstGen  the value for art.cst_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCstGen(Double cstGen) {
        this.cstGen = cstGen;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cod_onu
     * @return  the value of art.cod_onu
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCodOnu() {
        return codOnu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cod_onu
     * @param codOnu  the value for art.cod_onu
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCodOnu(Long codOnu) {
        this.codOnu = codOnu;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cat_tpt
     * @return  the value of art.cat_tpt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCatTpt() {
        return catTpt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cat_tpt
     * @param catTpt  the value for art.cat_tpt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCatTpt(Long catTpt) {
        this.catTpt = catTpt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cos_grp
     * @return  the value of art.cos_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCosGrp() {
        return cosGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cos_grp
     * @param cosGrp  the value for art.cos_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCosGrp(Long cosGrp) {
        this.cosGrp = cosGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mp_id
     * @return  the value of art.mp_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getMpId() {
        return mpId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mp_id
     * @param mpId  the value for art.mp_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMpId(String mpId) {
        this.mpId = mpId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mp_name
     * @return  the value of art.mp_name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getMpName() {
        return mpName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mp_name
     * @param mpName  the value for art.mp_name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMpName(String mpName) {
        this.mpName = mpName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.cod_cpt_opf
     * @return  the value of art.cod_cpt_opf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCodCptOpf() {
        return codCptOpf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.cod_cpt_opf
     * @param codCptOpf  the value for art.cod_cpt_opf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCodCptOpf(Long codCptOpf) {
        this.codCptOpf = codCptOpf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.b_no_stk
     * @return  the value of art.b_no_stk
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getbNoStk() {
        return bNoStk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.b_no_stk
     * @param bNoStk  the value for art.b_no_stk
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setbNoStk(Short bNoStk) {
        this.bNoStk = bNoStk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.ref_ant
     * @return  the value of art.ref_ant
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRefAnt() {
        return refAnt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.ref_ant
     * @param refAnt  the value for art.ref_ant
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRefAnt(String refAnt) {
        this.refAnt = refAnt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.emb_cls
     * @return  the value of art.emb_cls
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEmbCls() {
        return embCls;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.emb_cls
     * @param embCls  the value for art.emb_cls
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEmbCls(Long embCls) {
        this.embCls = embCls;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.mp_ref
     * @return  the value of art.mp_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getMpRef() {
        return mpRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.mp_ref
     * @param mpRef  the value for art.mp_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMpRef(String mpRef) {
        this.mpRef = mpRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column art.pso_ent
     * @return  the value of art.pso_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoEnt() {
        return psoEnt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column art.pso_ent
     * @param psoEnt  the value for art.pso_ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoEnt(Double psoEnt) {
        this.psoEnt = psoEnt;
    }
}