package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class CalArt implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Integer sqlId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date sqlModTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ref;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String nameAbr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long pso;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.pso_max
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long psoMax;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.pso_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long psoMed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.cst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double cstPrd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artPla;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.cal_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String calGrp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long catArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long altUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date altTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long modUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date modTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long offUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date offTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short off;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.cal_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String calCom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cal_art.fct_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double fctCst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table cal_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.sql_id
     * @return  the value of cal_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Integer getSqlId() {
        return sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.sql_id
     * @param sqlId  the value for cal_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlId(Integer sqlId) {
        this.sqlId = sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.sql_mod_tim
     * @return  the value of cal_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getSqlModTim() {
        return sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.sql_mod_tim
     * @param sqlModTim  the value for cal_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlModTim(Date sqlModTim) {
        this.sqlModTim = sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.id
     * @return  the value of cal_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.id
     * @param id  the value for cal_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.ref
     * @return  the value of cal_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.ref
     * @param ref  the value for cal_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.name
     * @return  the value of cal_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.name
     * @param name  the value for cal_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.name_abr
     * @return  the value of cal_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getNameAbr() {
        return nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.name_abr
     * @param nameAbr  the value for cal_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setNameAbr(String nameAbr) {
        this.nameAbr = nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.pso
     * @return  the value of cal_art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPso() {
        return pso;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.pso
     * @param pso  the value for cal_art.pso
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPso(Long pso) {
        this.pso = pso;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.pso_max
     * @return  the value of cal_art.pso_max
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPsoMax() {
        return psoMax;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.pso_max
     * @param psoMax  the value for cal_art.pso_max
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoMax(Long psoMax) {
        this.psoMax = psoMax;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.pso_med
     * @return  the value of cal_art.pso_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPsoMed() {
        return psoMed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.pso_med
     * @param psoMed  the value for cal_art.pso_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoMed(Long psoMed) {
        this.psoMed = psoMed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.cst_prd
     * @return  the value of cal_art.cst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getCstPrd() {
        return cstPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.cst_prd
     * @param cstPrd  the value for cal_art.cst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCstPrd(Double cstPrd) {
        this.cstPrd = cstPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.art_pla
     * @return  the value of cal_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtPla() {
        return artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.art_pla
     * @param artPla  the value for cal_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtPla(Long artPla) {
        this.artPla = artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.cal_grp
     * @return  the value of cal_art.cal_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCalGrp() {
        return calGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.cal_grp
     * @param calGrp  the value for cal_art.cal_grp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCalGrp(String calGrp) {
        this.calGrp = calGrp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.cat_art
     * @return  the value of cal_art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCatArt() {
        return catArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.cat_art
     * @param catArt  the value for cal_art.cat_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCatArt(Long catArt) {
        this.catArt = catArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.alt_usr
     * @return  the value of cal_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getAltUsr() {
        return altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.alt_usr
     * @param altUsr  the value for cal_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltUsr(Long altUsr) {
        this.altUsr = altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.alt_tim
     * @return  the value of cal_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getAltTim() {
        return altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.alt_tim
     * @param altTim  the value for cal_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltTim(Date altTim) {
        this.altTim = altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.mod_usr
     * @return  the value of cal_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getModUsr() {
        return modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.mod_usr
     * @param modUsr  the value for cal_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModUsr(Long modUsr) {
        this.modUsr = modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.mod_tim
     * @return  the value of cal_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getModTim() {
        return modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.mod_tim
     * @param modTim  the value for cal_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModTim(Date modTim) {
        this.modTim = modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.off_usr
     * @return  the value of cal_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getOffUsr() {
        return offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.off_usr
     * @param offUsr  the value for cal_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffUsr(Long offUsr) {
        this.offUsr = offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.off_tim
     * @return  the value of cal_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getOffTim() {
        return offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.off_tim
     * @param offTim  the value for cal_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffTim(Date offTim) {
        this.offTim = offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.off
     * @return  the value of cal_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getOff() {
        return off;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.off
     * @param off  the value for cal_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOff(Short off) {
        this.off = off;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.cal_com
     * @return  the value of cal_art.cal_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCalCom() {
        return calCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.cal_com
     * @param calCom  the value for cal_art.cal_com
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCalCom(String calCom) {
        this.calCom = calCom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cal_art.fct_cst
     * @return  the value of cal_art.fct_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getFctCst() {
        return fctCst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cal_art.fct_cst
     * @param fctCst  the value for cal_art.fct_cst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setFctCst(Double fctCst) {
        this.fctCst = fctCst;
    }
}