package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class PtdAlm implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Integer sqlId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date sqlModTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long nro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.nro_ser
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String nroSer;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cja_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cjaNro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_brt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoBrt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_net
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoNet;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.fch
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date fch;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_net_ok
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoNetOk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_net_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoNetAju;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ptd_est
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ptdEst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_net_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoNetLin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoLin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cja_nro_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cjaNroLin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.tara
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double tara;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoPdt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short cnf;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short cal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short mst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short mstPrd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.alb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long alb;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long ctr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ent_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long entEntTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long ent;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.tar_cal_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long tarCalPla;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.com_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String comTip;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoCja;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.tara_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double taraCja;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_net_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoNetCja;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mrm_prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double mrmPrc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double pre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_dst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgDst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_mdr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgMdr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double prc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.prc_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double prcManMod;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgCal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgIi;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgAju;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long kgManMod;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cal_y_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short calYGen;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.por
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short por;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pre_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double preIi;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String obs;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.obs_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String obs2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long art;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artPla;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.trz
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String trz;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String gtin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String gtinDc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ref;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cab_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cabCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String cld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.etq_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String etqCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.etq_ref_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String etqRefCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long eje;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.emp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String emp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_a_mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgAMst;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ctr_prc_pnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long ctrPrcPnf;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.fch_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date fchCal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long altUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date altTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long plt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pso_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double psoPlt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ref_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String refPlt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.hor_ini
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date horIni;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.hor_fin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date horFin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.prt_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long prtPrd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.plt_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long pltNro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long modUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date modTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short off;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long offUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date offTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.zon
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long zon;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cfc1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cfc2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cal_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long calArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.art_cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artCfc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String cfcRef;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.art_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artRef;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.plt_mxt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short pltMxt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cfcNro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long mrc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_x_pla_c
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cfcXPlaC;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cfc_x_pla_u
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cfcXPlaU;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ctr_prv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long ctrPrv;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.sbt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long sbt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.art_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artCja;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cja_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cjaAsg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cja_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long cjaPdt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgAsg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgPdt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.imp_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double impVta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.pre_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double preMed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.sbt_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long sbtArt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_des_clb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgDesClb;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.kg_a_liq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Double kgALiq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.ent_ctf_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long entCtfCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cod_cld_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long codCld1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.cod_cld_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long codCld2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.avs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String avsCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.b_ctf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short bCtf;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.obs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String obsCld;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ptd_alm.prior
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long prior;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ptd_alm
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.sql_id
     * @return  the value of ptd_alm.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Integer getSqlId() {
        return sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.sql_id
     * @param sqlId  the value for ptd_alm.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlId(Integer sqlId) {
        this.sqlId = sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.sql_mod_tim
     * @return  the value of ptd_alm.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getSqlModTim() {
        return sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.sql_mod_tim
     * @param sqlModTim  the value for ptd_alm.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlModTim(Date sqlModTim) {
        this.sqlModTim = sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.id
     * @return  the value of ptd_alm.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.id
     * @param id  the value for ptd_alm.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.nro
     * @return  the value of ptd_alm.nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getNro() {
        return nro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.nro
     * @param nro  the value for ptd_alm.nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setNro(Long nro) {
        this.nro = nro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.nro_ser
     * @return  the value of ptd_alm.nro_ser
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getNroSer() {
        return nroSer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.nro_ser
     * @param nroSer  the value for ptd_alm.nro_ser
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setNroSer(String nroSer) {
        this.nroSer = nroSer;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cja_nro
     * @return  the value of ptd_alm.cja_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCjaNro() {
        return cjaNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cja_nro
     * @param cjaNro  the value for ptd_alm.cja_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCjaNro(Long cjaNro) {
        this.cjaNro = cjaNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_brt
     * @return  the value of ptd_alm.pso_brt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoBrt() {
        return psoBrt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_brt
     * @param psoBrt  the value for ptd_alm.pso_brt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoBrt(Double psoBrt) {
        this.psoBrt = psoBrt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_net
     * @return  the value of ptd_alm.pso_net
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoNet() {
        return psoNet;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_net
     * @param psoNet  the value for ptd_alm.pso_net
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoNet(Double psoNet) {
        this.psoNet = psoNet;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.fch
     * @return  the value of ptd_alm.fch
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getFch() {
        return fch;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.fch
     * @param fch  the value for ptd_alm.fch
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setFch(Date fch) {
        this.fch = fch;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_net_ok
     * @return  the value of ptd_alm.pso_net_ok
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoNetOk() {
        return psoNetOk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_net_ok
     * @param psoNetOk  the value for ptd_alm.pso_net_ok
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoNetOk(Double psoNetOk) {
        this.psoNetOk = psoNetOk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_net_aju
     * @return  the value of ptd_alm.pso_net_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoNetAju() {
        return psoNetAju;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_net_aju
     * @param psoNetAju  the value for ptd_alm.pso_net_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoNetAju(Double psoNetAju) {
        this.psoNetAju = psoNetAju;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ptd_est
     * @return  the value of ptd_alm.ptd_est
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getPtdEst() {
        return ptdEst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ptd_est
     * @param ptdEst  the value for ptd_alm.ptd_est
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPtdEst(String ptdEst) {
        this.ptdEst = ptdEst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_net_lin
     * @return  the value of ptd_alm.pso_net_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoNetLin() {
        return psoNetLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_net_lin
     * @param psoNetLin  the value for ptd_alm.pso_net_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoNetLin(Double psoNetLin) {
        this.psoNetLin = psoNetLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_lin
     * @return  the value of ptd_alm.pso_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoLin() {
        return psoLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_lin
     * @param psoLin  the value for ptd_alm.pso_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoLin(Double psoLin) {
        this.psoLin = psoLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cja_nro_lin
     * @return  the value of ptd_alm.cja_nro_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCjaNroLin() {
        return cjaNroLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cja_nro_lin
     * @param cjaNroLin  the value for ptd_alm.cja_nro_lin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCjaNroLin(Long cjaNroLin) {
        this.cjaNroLin = cjaNroLin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.tara
     * @return  the value of ptd_alm.tara
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getTara() {
        return tara;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.tara
     * @param tara  the value for ptd_alm.tara
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setTara(Double tara) {
        this.tara = tara;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_pdt
     * @return  the value of ptd_alm.pso_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoPdt() {
        return psoPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_pdt
     * @param psoPdt  the value for ptd_alm.pso_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoPdt(Double psoPdt) {
        this.psoPdt = psoPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.name
     * @return  the value of ptd_alm.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.name
     * @param name  the value for ptd_alm.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cnf
     * @return  the value of ptd_alm.cnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getCnf() {
        return cnf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cnf
     * @param cnf  the value for ptd_alm.cnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCnf(Short cnf) {
        this.cnf = cnf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cal
     * @return  the value of ptd_alm.cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getCal() {
        return cal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cal
     * @param cal  the value for ptd_alm.cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCal(Short cal) {
        this.cal = cal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mst
     * @return  the value of ptd_alm.mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getMst() {
        return mst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mst
     * @param mst  the value for ptd_alm.mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMst(Short mst) {
        this.mst = mst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mst_prd
     * @return  the value of ptd_alm.mst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getMstPrd() {
        return mstPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mst_prd
     * @param mstPrd  the value for ptd_alm.mst_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMstPrd(Short mstPrd) {
        this.mstPrd = mstPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.alb
     * @return  the value of ptd_alm.alb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getAlb() {
        return alb;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.alb
     * @param alb  the value for ptd_alm.alb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAlb(Long alb) {
        this.alb = alb;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ctr
     * @return  the value of ptd_alm.ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCtr() {
        return ctr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ctr
     * @param ctr  the value for ptd_alm.ctr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCtr(Long ctr) {
        this.ctr = ctr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ent_ent_tip
     * @return  the value of ptd_alm.ent_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEntEntTip() {
        return entEntTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ent_ent_tip
     * @param entEntTip  the value for ptd_alm.ent_ent_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEntEntTip(Long entEntTip) {
        this.entEntTip = entEntTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ent
     * @return  the value of ptd_alm.ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEnt() {
        return ent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ent
     * @param ent  the value for ptd_alm.ent
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEnt(Long ent) {
        this.ent = ent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.tar_cal_pla
     * @return  the value of ptd_alm.tar_cal_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getTarCalPla() {
        return tarCalPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.tar_cal_pla
     * @param tarCalPla  the value for ptd_alm.tar_cal_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setTarCalPla(Long tarCalPla) {
        this.tarCalPla = tarCalPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.com_tip
     * @return  the value of ptd_alm.com_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getComTip() {
        return comTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.com_tip
     * @param comTip  the value for ptd_alm.com_tip
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setComTip(String comTip) {
        this.comTip = comTip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_cja
     * @return  the value of ptd_alm.pso_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoCja() {
        return psoCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_cja
     * @param psoCja  the value for ptd_alm.pso_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoCja(Double psoCja) {
        this.psoCja = psoCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.tara_cja
     * @return  the value of ptd_alm.tara_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getTaraCja() {
        return taraCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.tara_cja
     * @param taraCja  the value for ptd_alm.tara_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setTaraCja(Double taraCja) {
        this.taraCja = taraCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_net_cja
     * @return  the value of ptd_alm.pso_net_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoNetCja() {
        return psoNetCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_net_cja
     * @param psoNetCja  the value for ptd_alm.pso_net_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoNetCja(Double psoNetCja) {
        this.psoNetCja = psoNetCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mrm_prc
     * @return  the value of ptd_alm.mrm_prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getMrmPrc() {
        return mrmPrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mrm_prc
     * @param mrmPrc  the value for ptd_alm.mrm_prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMrmPrc(Double mrmPrc) {
        this.mrmPrc = mrmPrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pre
     * @return  the value of ptd_alm.pre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPre() {
        return pre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pre
     * @param pre  the value for ptd_alm.pre
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPre(Double pre) {
        this.pre = pre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_dst
     * @return  the value of ptd_alm.kg_dst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgDst() {
        return kgDst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_dst
     * @param kgDst  the value for ptd_alm.kg_dst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgDst(Double kgDst) {
        this.kgDst = kgDst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_mdr
     * @return  the value of ptd_alm.kg_mdr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgMdr() {
        return kgMdr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_mdr
     * @param kgMdr  the value for ptd_alm.kg_mdr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgMdr(Double kgMdr) {
        this.kgMdr = kgMdr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.prc
     * @return  the value of ptd_alm.prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPrc() {
        return prc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.prc
     * @param prc  the value for ptd_alm.prc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrc(Double prc) {
        this.prc = prc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.prc_man_mod
     * @return  the value of ptd_alm.prc_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPrcManMod() {
        return prcManMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.prc_man_mod
     * @param prcManMod  the value for ptd_alm.prc_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrcManMod(Double prcManMod) {
        this.prcManMod = prcManMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_cal
     * @return  the value of ptd_alm.kg_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgCal() {
        return kgCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_cal
     * @param kgCal  the value for ptd_alm.kg_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgCal(Double kgCal) {
        this.kgCal = kgCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_ii
     * @return  the value of ptd_alm.kg_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgIi() {
        return kgIi;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_ii
     * @param kgIi  the value for ptd_alm.kg_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgIi(Double kgIi) {
        this.kgIi = kgIi;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_aju
     * @return  the value of ptd_alm.kg_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgAju() {
        return kgAju;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_aju
     * @param kgAju  the value for ptd_alm.kg_aju
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgAju(Double kgAju) {
        this.kgAju = kgAju;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_man_mod
     * @return  the value of ptd_alm.kg_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getKgManMod() {
        return kgManMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_man_mod
     * @param kgManMod  the value for ptd_alm.kg_man_mod
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgManMod(Long kgManMod) {
        this.kgManMod = kgManMod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cal_y_gen
     * @return  the value of ptd_alm.cal_y_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getCalYGen() {
        return calYGen;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cal_y_gen
     * @param calYGen  the value for ptd_alm.cal_y_gen
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCalYGen(Short calYGen) {
        this.calYGen = calYGen;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.por
     * @return  the value of ptd_alm.por
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getPor() {
        return por;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.por
     * @param por  the value for ptd_alm.por
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPor(Short por) {
        this.por = por;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pre_ii
     * @return  the value of ptd_alm.pre_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPreIi() {
        return preIi;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pre_ii
     * @param preIi  the value for ptd_alm.pre_ii
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPreIi(Double preIi) {
        this.preIi = preIi;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.obs
     * @return  the value of ptd_alm.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getObs() {
        return obs;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.obs
     * @param obs  the value for ptd_alm.obs
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setObs(String obs) {
        this.obs = obs;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.obs_2
     * @return  the value of ptd_alm.obs_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getObs2() {
        return obs2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.obs_2
     * @param obs2  the value for ptd_alm.obs_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setObs2(String obs2) {
        this.obs2 = obs2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.art
     * @return  the value of ptd_alm.art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArt() {
        return art;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.art
     * @param art  the value for ptd_alm.art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArt(Long art) {
        this.art = art;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.art_pla
     * @return  the value of ptd_alm.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtPla() {
        return artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.art_pla
     * @param artPla  the value for ptd_alm.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtPla(Long artPla) {
        this.artPla = artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.trz
     * @return  the value of ptd_alm.trz
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getTrz() {
        return trz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.trz
     * @param trz  the value for ptd_alm.trz
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setTrz(String trz) {
        this.trz = trz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.gtin
     * @return  the value of ptd_alm.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getGtin() {
        return gtin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.gtin
     * @param gtin  the value for ptd_alm.gtin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setGtin(String gtin) {
        this.gtin = gtin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.gtin_dc
     * @return  the value of ptd_alm.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getGtinDc() {
        return gtinDc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.gtin_dc
     * @param gtinDc  the value for ptd_alm.gtin_dc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setGtinDc(String gtinDc) {
        this.gtinDc = gtinDc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ref
     * @return  the value of ptd_alm.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ref
     * @param ref  the value for ptd_alm.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cab_cld
     * @return  the value of ptd_alm.cab_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCabCld() {
        return cabCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cab_cld
     * @param cabCld  the value for ptd_alm.cab_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCabCld(Long cabCld) {
        this.cabCld = cabCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cld
     * @return  the value of ptd_alm.cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCld() {
        return cld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cld
     * @param cld  the value for ptd_alm.cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCld(String cld) {
        this.cld = cld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.etq_cld
     * @return  the value of ptd_alm.etq_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getEtqCld() {
        return etqCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.etq_cld
     * @param etqCld  the value for ptd_alm.etq_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEtqCld(String etqCld) {
        this.etqCld = etqCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.etq_ref_cld
     * @return  the value of ptd_alm.etq_ref_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getEtqRefCld() {
        return etqRefCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.etq_ref_cld
     * @param etqRefCld  the value for ptd_alm.etq_ref_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEtqRefCld(String etqRefCld) {
        this.etqRefCld = etqRefCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.eje
     * @return  the value of ptd_alm.eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEje() {
        return eje;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.eje
     * @param eje  the value for ptd_alm.eje
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEje(Long eje) {
        this.eje = eje;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.emp
     * @return  the value of ptd_alm.emp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getEmp() {
        return emp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.emp
     * @param emp  the value for ptd_alm.emp
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEmp(String emp) {
        this.emp = emp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_a_mst
     * @return  the value of ptd_alm.kg_a_mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgAMst() {
        return kgAMst;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_a_mst
     * @param kgAMst  the value for ptd_alm.kg_a_mst
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgAMst(Double kgAMst) {
        this.kgAMst = kgAMst;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ctr_prc_pnf
     * @return  the value of ptd_alm.ctr_prc_pnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCtrPrcPnf() {
        return ctrPrcPnf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ctr_prc_pnf
     * @param ctrPrcPnf  the value for ptd_alm.ctr_prc_pnf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCtrPrcPnf(Long ctrPrcPnf) {
        this.ctrPrcPnf = ctrPrcPnf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.fch_cal
     * @return  the value of ptd_alm.fch_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getFchCal() {
        return fchCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.fch_cal
     * @param fchCal  the value for ptd_alm.fch_cal
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setFchCal(Date fchCal) {
        this.fchCal = fchCal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.alt_usr
     * @return  the value of ptd_alm.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getAltUsr() {
        return altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.alt_usr
     * @param altUsr  the value for ptd_alm.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltUsr(Long altUsr) {
        this.altUsr = altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.alt_tim
     * @return  the value of ptd_alm.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getAltTim() {
        return altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.alt_tim
     * @param altTim  the value for ptd_alm.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltTim(Date altTim) {
        this.altTim = altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.plt
     * @return  the value of ptd_alm.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPlt() {
        return plt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.plt
     * @param plt  the value for ptd_alm.plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPlt(Long plt) {
        this.plt = plt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pso_plt
     * @return  the value of ptd_alm.pso_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPsoPlt() {
        return psoPlt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pso_plt
     * @param psoPlt  the value for ptd_alm.pso_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPsoPlt(Double psoPlt) {
        this.psoPlt = psoPlt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ref_plt
     * @return  the value of ptd_alm.ref_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRefPlt() {
        return refPlt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ref_plt
     * @param refPlt  the value for ptd_alm.ref_plt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRefPlt(String refPlt) {
        this.refPlt = refPlt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.hor_ini
     * @return  the value of ptd_alm.hor_ini
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getHorIni() {
        return horIni;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.hor_ini
     * @param horIni  the value for ptd_alm.hor_ini
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setHorIni(Date horIni) {
        this.horIni = horIni;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.hor_fin
     * @return  the value of ptd_alm.hor_fin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getHorFin() {
        return horFin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.hor_fin
     * @param horFin  the value for ptd_alm.hor_fin
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setHorFin(Date horFin) {
        this.horFin = horFin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.prt_prd
     * @return  the value of ptd_alm.prt_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPrtPrd() {
        return prtPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.prt_prd
     * @param prtPrd  the value for ptd_alm.prt_prd
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrtPrd(Long prtPrd) {
        this.prtPrd = prtPrd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.plt_nro
     * @return  the value of ptd_alm.plt_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPltNro() {
        return pltNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.plt_nro
     * @param pltNro  the value for ptd_alm.plt_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPltNro(Long pltNro) {
        this.pltNro = pltNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mod_usr
     * @return  the value of ptd_alm.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getModUsr() {
        return modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mod_usr
     * @param modUsr  the value for ptd_alm.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModUsr(Long modUsr) {
        this.modUsr = modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mod_tim
     * @return  the value of ptd_alm.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getModTim() {
        return modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mod_tim
     * @param modTim  the value for ptd_alm.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModTim(Date modTim) {
        this.modTim = modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.off
     * @return  the value of ptd_alm.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getOff() {
        return off;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.off
     * @param off  the value for ptd_alm.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOff(Short off) {
        this.off = off;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.off_usr
     * @return  the value of ptd_alm.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getOffUsr() {
        return offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.off_usr
     * @param offUsr  the value for ptd_alm.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffUsr(Long offUsr) {
        this.offUsr = offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.off_tim
     * @return  the value of ptd_alm.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getOffTim() {
        return offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.off_tim
     * @param offTim  the value for ptd_alm.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffTim(Date offTim) {
        this.offTim = offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.zon
     * @return  the value of ptd_alm.zon
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getZon() {
        return zon;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.zon
     * @param zon  the value for ptd_alm.zon
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setZon(Long zon) {
        this.zon = zon;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_1
     * @return  the value of ptd_alm.cfc_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCfc1() {
        return cfc1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_1
     * @param cfc1  the value for ptd_alm.cfc_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfc1(Long cfc1) {
        this.cfc1 = cfc1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_2
     * @return  the value of ptd_alm.cfc_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCfc2() {
        return cfc2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_2
     * @param cfc2  the value for ptd_alm.cfc_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfc2(Long cfc2) {
        this.cfc2 = cfc2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cal_art
     * @return  the value of ptd_alm.cal_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCalArt() {
        return calArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cal_art
     * @param calArt  the value for ptd_alm.cal_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCalArt(Long calArt) {
        this.calArt = calArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.art_cfc
     * @return  the value of ptd_alm.art_cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtCfc() {
        return artCfc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.art_cfc
     * @param artCfc  the value for ptd_alm.art_cfc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtCfc(Long artCfc) {
        this.artCfc = artCfc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_ref
     * @return  the value of ptd_alm.cfc_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getCfcRef() {
        return cfcRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_ref
     * @param cfcRef  the value for ptd_alm.cfc_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfcRef(String cfcRef) {
        this.cfcRef = cfcRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.art_ref
     * @return  the value of ptd_alm.art_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtRef() {
        return artRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.art_ref
     * @param artRef  the value for ptd_alm.art_ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtRef(Long artRef) {
        this.artRef = artRef;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.plt_mxt
     * @return  the value of ptd_alm.plt_mxt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getPltMxt() {
        return pltMxt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.plt_mxt
     * @param pltMxt  the value for ptd_alm.plt_mxt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPltMxt(Short pltMxt) {
        this.pltMxt = pltMxt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_nro
     * @return  the value of ptd_alm.cfc_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCfcNro() {
        return cfcNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_nro
     * @param cfcNro  the value for ptd_alm.cfc_nro
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfcNro(Long cfcNro) {
        this.cfcNro = cfcNro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.mrc
     * @return  the value of ptd_alm.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getMrc() {
        return mrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.mrc
     * @param mrc  the value for ptd_alm.mrc
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setMrc(Long mrc) {
        this.mrc = mrc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_x_pla_c
     * @return  the value of ptd_alm.cfc_x_pla_c
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCfcXPlaC() {
        return cfcXPlaC;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_x_pla_c
     * @param cfcXPlaC  the value for ptd_alm.cfc_x_pla_c
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfcXPlaC(Long cfcXPlaC) {
        this.cfcXPlaC = cfcXPlaC;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cfc_x_pla_u
     * @return  the value of ptd_alm.cfc_x_pla_u
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCfcXPlaU() {
        return cfcXPlaU;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cfc_x_pla_u
     * @param cfcXPlaU  the value for ptd_alm.cfc_x_pla_u
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCfcXPlaU(Long cfcXPlaU) {
        this.cfcXPlaU = cfcXPlaU;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ctr_prv
     * @return  the value of ptd_alm.ctr_prv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCtrPrv() {
        return ctrPrv;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ctr_prv
     * @param ctrPrv  the value for ptd_alm.ctr_prv
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCtrPrv(Long ctrPrv) {
        this.ctrPrv = ctrPrv;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.sbt
     * @return  the value of ptd_alm.sbt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getSbt() {
        return sbt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.sbt
     * @param sbt  the value for ptd_alm.sbt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSbt(Long sbt) {
        this.sbt = sbt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.art_cja
     * @return  the value of ptd_alm.art_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtCja() {
        return artCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.art_cja
     * @param artCja  the value for ptd_alm.art_cja
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtCja(Long artCja) {
        this.artCja = artCja;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cja_asg
     * @return  the value of ptd_alm.cja_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCjaAsg() {
        return cjaAsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cja_asg
     * @param cjaAsg  the value for ptd_alm.cja_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCjaAsg(Long cjaAsg) {
        this.cjaAsg = cjaAsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cja_pdt
     * @return  the value of ptd_alm.cja_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCjaPdt() {
        return cjaPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cja_pdt
     * @param cjaPdt  the value for ptd_alm.cja_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCjaPdt(Long cjaPdt) {
        this.cjaPdt = cjaPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_asg
     * @return  the value of ptd_alm.kg_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgAsg() {
        return kgAsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_asg
     * @param kgAsg  the value for ptd_alm.kg_asg
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgAsg(Double kgAsg) {
        this.kgAsg = kgAsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_pdt
     * @return  the value of ptd_alm.kg_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgPdt() {
        return kgPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_pdt
     * @param kgPdt  the value for ptd_alm.kg_pdt
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgPdt(Double kgPdt) {
        this.kgPdt = kgPdt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.imp_vta
     * @return  the value of ptd_alm.imp_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getImpVta() {
        return impVta;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.imp_vta
     * @param impVta  the value for ptd_alm.imp_vta
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setImpVta(Double impVta) {
        this.impVta = impVta;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.pre_med
     * @return  the value of ptd_alm.pre_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getPreMed() {
        return preMed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.pre_med
     * @param preMed  the value for ptd_alm.pre_med
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPreMed(Double preMed) {
        this.preMed = preMed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.sbt_art
     * @return  the value of ptd_alm.sbt_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getSbtArt() {
        return sbtArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.sbt_art
     * @param sbtArt  the value for ptd_alm.sbt_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSbtArt(Long sbtArt) {
        this.sbtArt = sbtArt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_des_clb
     * @return  the value of ptd_alm.kg_des_clb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgDesClb() {
        return kgDesClb;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_des_clb
     * @param kgDesClb  the value for ptd_alm.kg_des_clb
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgDesClb(Double kgDesClb) {
        this.kgDesClb = kgDesClb;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.kg_a_liq
     * @return  the value of ptd_alm.kg_a_liq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Double getKgALiq() {
        return kgALiq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.kg_a_liq
     * @param kgALiq  the value for ptd_alm.kg_a_liq
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setKgALiq(Double kgALiq) {
        this.kgALiq = kgALiq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.ent_ctf_cld
     * @return  the value of ptd_alm.ent_ctf_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getEntCtfCld() {
        return entCtfCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.ent_ctf_cld
     * @param entCtfCld  the value for ptd_alm.ent_ctf_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setEntCtfCld(Long entCtfCld) {
        this.entCtfCld = entCtfCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cod_cld_1
     * @return  the value of ptd_alm.cod_cld_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCodCld1() {
        return codCld1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cod_cld_1
     * @param codCld1  the value for ptd_alm.cod_cld_1
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCodCld1(Long codCld1) {
        this.codCld1 = codCld1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.cod_cld_2
     * @return  the value of ptd_alm.cod_cld_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getCodCld2() {
        return codCld2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.cod_cld_2
     * @param codCld2  the value for ptd_alm.cod_cld_2
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setCodCld2(Long codCld2) {
        this.codCld2 = codCld2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.avs_cld
     * @return  the value of ptd_alm.avs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getAvsCld() {
        return avsCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.avs_cld
     * @param avsCld  the value for ptd_alm.avs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAvsCld(String avsCld) {
        this.avsCld = avsCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.b_ctf
     * @return  the value of ptd_alm.b_ctf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getbCtf() {
        return bCtf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.b_ctf
     * @param bCtf  the value for ptd_alm.b_ctf
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setbCtf(Short bCtf) {
        this.bCtf = bCtf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.obs_cld
     * @return  the value of ptd_alm.obs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getObsCld() {
        return obsCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.obs_cld
     * @param obsCld  the value for ptd_alm.obs_cld
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setObsCld(String obsCld) {
        this.obsCld = obsCld;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ptd_alm.prior
     * @return  the value of ptd_alm.prior
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getPrior() {
        return prior;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ptd_alm.prior
     * @param prior  the value for ptd_alm.prior
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setPrior(Long prior) {
        this.prior = prior;
    }
}