package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.enums.ClienteEnum;

public class TClientesMaterialesVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private Integer           idCliente;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_operadores.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            nombreCliente;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.id_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private Integer           idMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_operadores.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            nombreMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.iva
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private Integer           iva;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_operadores.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            descripcionIva;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.precio_kg
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            precioKg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_operadores.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuarioCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_operadores.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuarioModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_clientes_materiales.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_clientes_materiales
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the idCliente
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * @param idCliente the idCliente to set
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * @return the nombreCliente
     */
    public String getNombreCliente() {
        return nombreCliente;
    }

    /**
     * @param nombreCliente the nombreCliente to set
     */
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    /**
     * @return the idMaterial
     */
    public Integer getIdMaterial() {
        return idMaterial;
    }

    /**
     * @param idMaterial the idMaterial to set
     */
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }

    /**
     * @return the nombreMaterial
     */
    public String getNombreMaterial() {
        return nombreMaterial;
    }

    /**
     * @param nombreMaterial the nombreMaterial to set
     */
    public void setNombreMaterial(String nombreMaterial) {
        this.nombreMaterial = nombreMaterial;
    }

    /**
     * @return the iva
     */
    public Integer getIva() {
        return iva;
    }

    /**
     * @param iva the iva to set
     */
    public void setIva(Integer iva) {
        this.iva = iva;
    }

    /**
     * @return the precioKg
     */
    public String getPrecioKg() {
        return precioKg;
    }

    /**
     * @param precioKg the precioKg to set
     */
    public void setPrecioKg(String precioKg) {
        this.precioKg = precioKg;
    }

    /**
     * @return the usuCrea
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * @param usuCrea the usuCrea to set
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * @return the usuarioCrea
     */
    public String getUsuarioCrea() {
        return usuarioCrea;
    }

    /**
     * @param usuarioCrea the usuarioCrea to set
     */
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    /**
     * @return the fechaCrea
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * @param fechaCrea the fechaCrea to set
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * @return the usuModifica
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * @param usuModifica the usuModifica to set
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * @return the usuarioModifica
     */
    public String getUsuarioModifica() {
        return usuarioModifica;
    }

    /**
     * @param usuarioModifica the usuarioModifica to set
     */
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    /**
     * @return the fechaModifica
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * @param fechaModifica the fechaModifica to set
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * @return the estado
     */
    public String getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * @return the descripcionIva
     */
    public String getDescripcionIva() {
        return descripcionIva;
    }

    /**
     * @param descripcionIva the descripcionIva to set
     */
    public void setDescripcionIva(String descripcionIva) {
        this.descripcionIva = descripcionIva;
    }

    /**
     * Constructor a partir de TClientesMateriales
     * @param co El objeto con los datos a nutrir.
     */
    public TClientesMaterialesVista(TClientesMateriales c) {
        DecimalFormat df = new DecimalFormat("#,##0.000");
        this.estado = c.getEstado().equals(ClienteEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(c.getFechaCrea());
        this.fechaModifica = c.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(c.getFechaModifica()) : "-";
        this.idCliente = c.getIdCliente();
        this.idMaterial = c.getIdMaterial();
        this.iva = c.getIva();
        this.descripcionIva = "";
        this.nombreCliente = "";
        this.nombreMaterial = "";
        this.precioKg = df.format(c.getPrecioKg());
        this.usuarioCrea = "";
        this.usuarioModifica = "";
        this.usuCrea = "" + c.getUsuCrea();
        this.usuModifica = "" + c.getUsuModifica();
    }
}