package com.dina.genasoft.db.entity;

import java.io.Serializable;

public class TColumnasTablasEmpleado implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.id
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.id_empleado
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private Integer idEmpleado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.nombre_pantalla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private String nombrePantalla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.id_tabla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private Integer idTabla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private String campo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_columnas_tablas_empleado.orden_campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private Integer ordenCampo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_columnas_tablas_empleado
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.id
     *
     * @return the value of t_columnas_tablas_empleado.id
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.id
     *
     * @param id the value for t_columnas_tablas_empleado.id
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.id_empleado
     *
     * @return the value of t_columnas_tablas_empleado.id_empleado
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public Integer getIdEmpleado() {
        return idEmpleado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.id_empleado
     *
     * @param idEmpleado the value for t_columnas_tablas_empleado.id_empleado
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.nombre_pantalla
     *
     * @return the value of t_columnas_tablas_empleado.nombre_pantalla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public String getNombrePantalla() {
        return nombrePantalla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.nombre_pantalla
     *
     * @param nombrePantalla the value for t_columnas_tablas_empleado.nombre_pantalla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setNombrePantalla(String nombrePantalla) {
        this.nombrePantalla = nombrePantalla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.id_tabla
     *
     * @return the value of t_columnas_tablas_empleado.id_tabla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public Integer getIdTabla() {
        return idTabla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.id_tabla
     *
     * @param idTabla the value for t_columnas_tablas_empleado.id_tabla
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setIdTabla(Integer idTabla) {
        this.idTabla = idTabla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.campo
     *
     * @return the value of t_columnas_tablas_empleado.campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public String getCampo() {
        return campo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.campo
     *
     * @param campo the value for t_columnas_tablas_empleado.campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setCampo(String campo) {
        this.campo = campo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_columnas_tablas_empleado.orden_campo
     *
     * @return the value of t_columnas_tablas_empleado.orden_campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public Integer getOrdenCampo() {
        return ordenCampo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_columnas_tablas_empleado.orden_campo
     *
     * @param ordenCampo the value for t_columnas_tablas_empleado.orden_campo
     *
     * @mbg.generated Thu Feb 25 12:48:55 CET 2021
     */
    public void setOrdenCampo(Integer ordenCampo) {
        this.ordenCampo = ordenCampo;
    }
}