package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

import com.dina.genasoft.utils.Utils;

public class TControlProductoTerminadoPesajesCajaVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.id
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.id_control_producto_terminado
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            idControlProductoTerminado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.valor
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            valor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.orden
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            orden;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.usu_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.fecha_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.usu_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_pesajes_caja.fecha_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_control_producto_terminado_pesajes_caja
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.id
     * @return  the value of t_control_producto_terminado_pesajes_caja.id
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.id
     * @param id  the value for t_control_producto_terminado_pesajes_caja.id
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.id_control_producto_terminado
     * @return  the value of t_control_producto_terminado_pesajes_caja.id_control_producto_terminado
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getIdControlProductoTerminado() {
        return idControlProductoTerminado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.id_control_producto_terminado
     * @param idControlProductoTerminado  the value for t_control_producto_terminado_pesajes_caja.id_control_producto_terminado
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setIdControlProductoTerminado(String idControlProductoTerminado) {
        this.idControlProductoTerminado = idControlProductoTerminado;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.valor
     * @return  the value of t_control_producto_terminado_pesajes_caja.valor
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.valor
     * @param valor  the value for t_control_producto_terminado_pesajes_caja.valor
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setValor(String valor) {
        this.valor = valor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.orden
     * @return  the value of t_control_producto_terminado_pesajes_caja.orden
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.orden
     * @param orden  the value for t_control_producto_terminado_pesajes_caja.orden
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setOrden(String orden) {
        this.orden = orden;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.usu_crea
     * @return  the value of t_control_producto_terminado_pesajes_caja.usu_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.usu_crea
     * @param usuCrea  the value for t_control_producto_terminado_pesajes_caja.usu_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.fecha_crea
     * @return  the value of t_control_producto_terminado_pesajes_caja.fecha_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.fecha_crea
     * @param fechaCrea  the value for t_control_producto_terminado_pesajes_caja.fecha_crea
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.usu_modifica
     * @return  the value of t_control_producto_terminado_pesajes_caja.usu_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.usu_modifica
     * @param usuModifica  the value for t_control_producto_terminado_pesajes_caja.usu_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_pesajes_caja.fecha_modifica
     * @return  the value of t_control_producto_terminado_pesajes_caja.fecha_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_pesajes_caja.fecha_modifica
     * @param fechaModifica  the value for t_control_producto_terminado_pesajes_caja.fecha_modifica
     * @mbg.generated  Thu Apr 08 15:52:32 CEST 2021
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * Método que nos realiza la copia de los campos pasado por parametro a formato String.
     * @param pesCaja El objeto con los datos a copiar.
     */
    public void copiaDesdePesajeCaja(TControlProductoTerminadoPesajesCaja pesCaja) {
        DecimalFormat df = new DecimalFormat("#,##0.00");
        this.fechaCrea = pesCaja.getFechaCrea() != null ? new SimpleDateFormat("dd/MM/yyyy").format(pesCaja.getFechaCrea()) : "-";
        this.fechaModifica = pesCaja.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy").format(pesCaja.getFechaModifica()) : "-";
        this.id = Utils.convertirIntegerStringVista(pesCaja.getId());
        this.idControlProductoTerminado = Utils.convertirIntegerStringVista(pesCaja.getIdControlProductoTerminado());
        this.orden = Utils.convertirIntegerStringVista(pesCaja.getOrden());
        this.usuCrea = Utils.convertirIntegerStringVista(pesCaja.getUsuCrea());
        this.usuModifica = Utils.convertirIntegerStringVista(pesCaja.getUsuModifica());
        this.valor = pesCaja.getValor() != null ? df.format(pesCaja.getValor()) : df.format(Double.valueOf(0));
    }
}