package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TControlProductoTerminadoFotosHis implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.id
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Integer           id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.id_control_producto_terminado
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Integer           idControlProductoTerminado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.id_linea
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Integer           idLinea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.orden_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Integer           ordenFoto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.descripcion_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private String            descripcionFoto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.usu_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Integer           usuFoto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_control_producto_terminado_fotos_his.fecha_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private Date              fechaFoto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_control_producto_terminado_fotos_his
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.id
     * @return  the value of t_control_producto_terminado_fotos_his.id
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.id
     * @param id  the value for t_control_producto_terminado_fotos_his.id
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.id_control_producto_terminado
     * @return  the value of t_control_producto_terminado_fotos_his.id_control_producto_terminado
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Integer getIdControlProductoTerminado() {
        return idControlProductoTerminado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.id_control_producto_terminado
     * @param idControlProductoTerminado  the value for t_control_producto_terminado_fotos_his.id_control_producto_terminado
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setIdControlProductoTerminado(Integer idControlProductoTerminado) {
        this.idControlProductoTerminado = idControlProductoTerminado;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.id_linea
     * @return  the value of t_control_producto_terminado_fotos_his.id_linea
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Integer getIdLinea() {
        return idLinea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.id_linea
     * @param idLinea  the value for t_control_producto_terminado_fotos_his.id_linea
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.orden_foto
     * @return  the value of t_control_producto_terminado_fotos_his.orden_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Integer getOrdenFoto() {
        return ordenFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.orden_foto
     * @param ordenFoto  the value for t_control_producto_terminado_fotos_his.orden_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setOrdenFoto(Integer ordenFoto) {
        this.ordenFoto = ordenFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.descripcion_foto
     * @return  the value of t_control_producto_terminado_fotos_his.descripcion_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public String getDescripcionFoto() {
        return descripcionFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.descripcion_foto
     * @param descripcionFoto  the value for t_control_producto_terminado_fotos_his.descripcion_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setDescripcionFoto(String descripcionFoto) {
        this.descripcionFoto = descripcionFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.usu_foto
     * @return  the value of t_control_producto_terminado_fotos_his.usu_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Integer getUsuFoto() {
        return usuFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.usu_foto
     * @param usuFoto  the value for t_control_producto_terminado_fotos_his.usu_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setUsuFoto(Integer usuFoto) {
        this.usuFoto = usuFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_control_producto_terminado_fotos_his.fecha_foto
     * @return  the value of t_control_producto_terminado_fotos_his.fecha_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public Date getFechaFoto() {
        return fechaFoto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_control_producto_terminado_fotos_his.fecha_foto
     * @param fechaFoto  the value for t_control_producto_terminado_fotos_his.fecha_foto
     * @mbg.generated  Fri May 14 18:38:04 CEST 2021
     */
    public void setFechaFoto(Date fechaFoto) {
        this.fechaFoto = fechaFoto;
    }

    public void copiaDesdeFoto(TControlProductoTerminadoFotos foto) {
        this.descripcionFoto = foto.getDescripcionFoto();
        this.fechaFoto = foto.getFechaFoto();
        this.id = foto.getId();
        this.idControlProductoTerminado = foto.getIdControlProductoTerminado();
        this.idLinea = foto.getIdLinea();
        this.ordenFoto = foto.getOrdenFoto();
        this.usuFoto = foto.getUsuFoto();
    }
}