package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TDiametrosProducto implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_diametros_producto.id
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private Integer           id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_diametros_producto.diametro
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private String            diametro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_diametros_producto.identificacion
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private String            identificacion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_diametros_producto.usu_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private Integer           usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_diametros_producto.fecha_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private Date              fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_diametros_producto
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_diametros_producto.id
     * @return  the value of t_diametros_producto.id
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_diametros_producto.id
     * @param id  the value for t_diametros_producto.id
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_diametros_producto.diametro
     * @return  the value of t_diametros_producto.diametro
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public String getDiametro() {
        return diametro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_diametros_producto.diametro
     * @param diametro  the value for t_diametros_producto.diametro
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public void setDiametro(String diametro) {
        this.diametro = diametro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_diametros_producto.identificacion
     * @return  the value of t_diametros_producto.identificacion
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public String getIdentificacion() {
        return identificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_diametros_producto.identificacion
     * @param identificacion  the value for t_diametros_producto.identificacion
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_diametros_producto.usu_crea
     * @return  the value of t_diametros_producto.usu_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public Integer getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_diametros_producto.usu_crea
     * @param usuCrea  the value for t_diametros_producto.usu_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public void setUsuCrea(Integer usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_diametros_producto.fecha_crea
     * @return  the value of t_diametros_producto.fecha_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public Date getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_diametros_producto.fecha_crea
     * @param fechaCrea  the value for t_diametros_producto.fecha_crea
     * @mbg.generated  Tue Apr 20 17:55:47 CEST 2021
     */
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    @Override
    public String toString() {
        return diametro;
    }

}