package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.ClienteEnum;

public class TDireccionClienteVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idCliente;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.cod_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            codDireccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            direccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.poblacion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            poblacion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            provincia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            pais;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_direccion_cliente.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            codigoPostal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_direccion_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.id
     * @return  the value of t_direccion_cliente.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.id
     * @param id  the value for t_direccion_cliente.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.id_cliente
     * @return  the value of t_direccion_cliente.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.id_cliente
     * @param idCliente  the value for t_direccion_cliente.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.cod_direccion
     * @return  the value of t_direccion_cliente.cod_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getCodDireccion() {
        return codDireccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.cod_direccion
     * @param codDireccion  the value for t_direccion_cliente.cod_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setCodDireccion(String codDireccion) {
        this.codDireccion = codDireccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.direccion
     * @return  the value of t_direccion_cliente.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.direccion
     * @param direccion  the value for t_direccion_cliente.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.poblacion
     * @return  the value of t_direccion_cliente.poblacion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getPoblacion() {
        return poblacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.poblacion
     * @param poblacion  the value for t_direccion_cliente.poblacion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.provincia
     * @return  the value of t_direccion_cliente.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.provincia
     * @param provincia  the value for t_direccion_cliente.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.pais
     * @return  the value of t_direccion_cliente.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.pais
     * @param pais  the value for t_direccion_cliente.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.usu_crea
     * @return  the value of t_direccion_cliente.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.usu_crea
     * @param usuCrea  the value for t_direccion_cliente.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.fecha_crea
     * @return  the value of t_direccion_cliente.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.fecha_crea
     * @param fechaCrea  the value for t_direccion_cliente.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.usu_modifica
     * @return  the value of t_direccion_cliente.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.usu_modifica
     * @param usuModifica  the value for t_direccion_cliente.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.fecha_modifica
     * @return  the value of t_direccion_cliente.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.fecha_modifica
     * @param fechaModifica  the value for t_direccion_cliente.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_direccion_cliente.estado
     * @return  the value of t_direccion_cliente.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_direccion_cliente.estado
     * @param estado  the value for t_direccion_cliente.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * @return the codigoPostal
     */
    public String getCodigoPostal() {
        return codigoPostal;
    }

    /**
     * @param codigoPostal the codigoPostal to set
     */
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    /**
     * Constructor a partir de TDireccionCliente
     * @param co El objeto con los datos a nutrir.
     */
    public TDireccionClienteVista(TDireccionCliente dir) {
        this.codDireccion = Utils.formatearValorString(dir.getCodDireccion());
        this.direccion = Utils.formatearValorString(dir.getDireccion());
        this.estado = dir.getEstado().equals(ClienteEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(dir.getFechaCrea());
        this.fechaModifica = dir.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(dir.getFechaModifica()) : "-";
        this.id = "" + dir.getId();
        this.idCliente = "" + dir.getIdCliente();
        this.usuCrea = "" + dir.getUsuCrea();
        this.usuModifica = "" + dir.getUsuModifica();
        this.codigoPostal = dir.getCodigoPostal();
    }
}