package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.EmpleadoEnum;

public class TEmpleadosVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.nombre_usuario
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            nombreUsuario;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.id_externo
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            idExterno;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.password
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.codigo_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            codigoAcceso;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.nombre
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            nombre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.dni
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            dni;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.telefono
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            telefono;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.pais
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            pais;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.email
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.id_rol
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            idRol;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.fecha_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.usu_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.fecha_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_empleados.estado
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_empleados
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.id
     * @return  the value of t_empleados.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.id
     * @param id  the value for t_empleados.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.nombre_usuario
     * @return  the value of t_empleados.nombre_usuario
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.nombre_usuario
     * @param nombreUsuario  the value for t_empleados.nombre_usuario
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.id_externo
     * @return  the value of t_empleados.id_externo
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getIdExterno() {
        return idExterno;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.id_externo
     * @param idExterno  the value for t_empleados.id_externo
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setIdExterno(String idExterno) {
        this.idExterno = idExterno;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.password
     * @return  the value of t_empleados.password
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.password
     * @param password  the value for t_empleados.password
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.codigo_acceso
     * @return  the value of t_empleados.codigo_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getCodigoAcceso() {
        return codigoAcceso;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.codigo_acceso
     * @param codigoAcceso  the value for t_empleados.codigo_acceso
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setCodigoAcceso(String codigoAcceso) {
        this.codigoAcceso = codigoAcceso;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.nombre
     * @return  the value of t_empleados.nombre
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.nombre
     * @param nombre  the value for t_empleados.nombre
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.dni
     * @return  the value of t_empleados.dni
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.dni
     * @param dni  the value for t_empleados.dni
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setDni(String dni) {
        this.dni = dni;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.telefono
     * @return  the value of t_empleados.telefono
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.telefono
     * @param telefono  the value for t_empleados.telefono
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.pais
     * @return  the value of t_empleados.pais
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.pais
     * @param pais  the value for t_empleados.pais
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.email
     * @return  the value of t_empleados.email
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.email
     * @param email  the value for t_empleados.email
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.id_rol
     * @return  the value of t_empleados.id_rol
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getIdRol() {
        return idRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.id_rol
     * @param idRol  the value for t_empleados.id_rol
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.usu_crea
     * @return  the value of t_empleados.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.usu_crea
     * @param usuCrea  the value for t_empleados.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.fecha_crea
     * @return  the value of t_empleados.fecha_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.fecha_crea
     * @param fechaCrea  the value for t_empleados.fecha_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.usu_modifica
     * @return  the value of t_empleados.usu_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.usu_modifica
     * @param usuModifica  the value for t_empleados.usu_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.fecha_modifica
     * @return  the value of t_empleados.fecha_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.fecha_modifica
     * @param fechaModifica  the value for t_empleados.fecha_modifica
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_empleados.estado
     * @return  the value of t_empleados.estado
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_empleados.estado
     * @param estado  the value for t_empleados.estado
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Constructor a partir de TEmpleados
     * @param co El objeto con los datos a nutrir.
     */
    public TEmpleadosVista(TEmpleados e) {
        this.codigoAcceso = Utils.formatearValorString(e.getCodigoAcceso());
        this.dni = Utils.formatearValorString(e.getDni());
        this.email = Utils.formatearValorString(e.getEmail());
        this.estado = e.getEstado().equals(EmpleadoEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(e.getFechaCrea());
        this.fechaModifica = e.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(e.getFechaModifica()) : "-";
        this.id = "" + e.getId();
        this.idExterno = Utils.formatearValorString(e.getIdExterno());
        this.idRol = "" + e.getIdRol();
        this.nombre = Utils.formatearValorString(e.getNombre());
        this.nombreUsuario = Utils.formatearValorString(e.getNombreUsuario());
        this.pais = Utils.formatearValorString(e.getPais());
        this.password = Utils.formatearValorString(e.getPassword());
        this.telefono = Utils.formatearValorString(e.getTelefono());
        this.usuCrea = "" + e.getUsuCrea();
        this.usuModifica = "" + e.getUsuModifica();
    }

}