package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.MaterialEnum;

public class TMaterialesVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.referencia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            referencia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.descripcion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            descripcion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.ler
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            ler;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.id_familia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idFamilia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.precio
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            precio;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.iva
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            iva;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_materiales.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_materiales
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.id
     * @return  the value of t_materiales.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.id
     * @param id  the value for t_materiales.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.referencia
     * @return  the value of t_materiales.referencia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getReferencia() {
        return referencia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.referencia
     * @param referencia  the value for t_materiales.referencia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.descripcion
     * @return  the value of t_materiales.descripcion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.descripcion
     * @param descripcion  the value for t_materiales.descripcion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.ler
     * @return  the value of t_materiales.ler
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getLer() {
        return ler;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.ler
     * @param ler  the value for t_materiales.ler
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setLer(String ler) {
        this.ler = ler;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.id_familia
     * @return  the value of t_materiales.id_familia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdFamilia() {
        return idFamilia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.id_familia
     * @param idFamilia  the value for t_materiales.id_familia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdFamilia(String idFamilia) {
        this.idFamilia = idFamilia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.precio
     * @return  the value of t_materiales.precio
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getPrecio() {
        return precio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.precio
     * @param precio  the value for t_materiales.precio
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setPrecio(String precio) {
        this.precio = precio;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.iva
     * @return  the value of t_materiales.iva
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.iva
     * @param iva  the value for t_materiales.iva
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIva(String iva) {
        this.iva = iva;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.usu_crea
     * @return  the value of t_materiales.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.usu_crea
     * @param usuCrea  the value for t_materiales.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.fecha_crea
     * @return  the value of t_materiales.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.fecha_crea
     * @param fechaCrea  the value for t_materiales.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.usu_modifica
     * @return  the value of t_materiales.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.usu_modifica
     * @param usuModifica  the value for t_materiales.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.fecha_modifica
     * @return  the value of t_materiales.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.fecha_modifica
     * @param fechaModifica  the value for t_materiales.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_materiales.estado
     * @return  the value of t_materiales.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_materiales.estado
     * @param estado  the value for t_materiales.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Constructor a partir de TMateriales
     * @param m El objeto con los datos a nutrir.
     */
    public TMaterialesVista(TMateriales m) {
        DecimalFormat df = new DecimalFormat("#,##0.000");
        this.descripcion = Utils.formatearValorString(m.getDescripcion());
        this.estado = m.getEstado().equals(MaterialEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(m.getFechaCrea());
        this.fechaModifica = m.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(m.getFechaModifica()) : "-";
        this.id = "" + m.getId();
        this.idFamilia = "" + m.getIdFamilia();
        this.iva = "" + m.getIva();
        this.ler = Utils.formatearValorString(m.getLer());
        this.precio = df.format(m.getPrecio());
        this.referencia = Utils.formatearValorString(m.getReferencia());
        this.usuCrea = "" + m.getUsuCrea();
        this.usuModifica = "" + m.getUsuModifica();
    }
}