package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.PesajesEnum;

public class TPesajesVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.numero_albaran
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            numeroAlbaran;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idCliente;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.id_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idDireccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.fecha_pesaje
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaPesaje;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.obra
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            obra;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.origen
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            origen;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.destino
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            destino;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.id_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.ref_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            refMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.ler_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            lerMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.desc_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            descMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.kgs_bruto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            kgsBruto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.kgs_neto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            kgsNeto;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.tara
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            tara;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.id_factura
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            idFactura;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_pesajes.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_pesajes
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.id
     * @return  the value of t_pesajes.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.id
     * @param id  the value for t_pesajes.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.numero_albaran
     * @return  the value of t_pesajes.numero_albaran
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getNumeroAlbaran() {
        return numeroAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.numero_albaran
     * @param numeroAlbaran  the value for t_pesajes.numero_albaran
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setNumeroAlbaran(String numeroAlbaran) {
        this.numeroAlbaran = numeroAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.id_cliente
     * @return  the value of t_pesajes.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.id_cliente
     * @param idCliente  the value for t_pesajes.id_cliente
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.id_direccion
     * @return  the value of t_pesajes.id_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdDireccion() {
        return idDireccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.id_direccion
     * @param idDireccion  the value for t_pesajes.id_direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdDireccion(String idDireccion) {
        this.idDireccion = idDireccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.fecha_pesaje
     * @return  the value of t_pesajes.fecha_pesaje
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaPesaje() {
        return fechaPesaje;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.fecha_pesaje
     * @param fechaPesaje  the value for t_pesajes.fecha_pesaje
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaPesaje(String fechaPesaje) {
        this.fechaPesaje = fechaPesaje;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.obra
     * @return  the value of t_pesajes.obra
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getObra() {
        return obra;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.obra
     * @param obra  the value for t_pesajes.obra
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setObra(String obra) {
        this.obra = obra;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.origen
     * @return  the value of t_pesajes.origen
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.origen
     * @param origen  the value for t_pesajes.origen
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.destino
     * @return  the value of t_pesajes.destino
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getDestino() {
        return destino;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.destino
     * @param destino  the value for t_pesajes.destino
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setDestino(String destino) {
        this.destino = destino;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.id_material
     * @return  the value of t_pesajes.id_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdMaterial() {
        return idMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.id_material
     * @param idMaterial  the value for t_pesajes.id_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdMaterial(String idMaterial) {
        this.idMaterial = idMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.ref_material
     * @return  the value of t_pesajes.ref_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getRefMaterial() {
        return refMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.ref_material
     * @param refMaterial  the value for t_pesajes.ref_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setRefMaterial(String refMaterial) {
        this.refMaterial = refMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.ler_material
     * @return  the value of t_pesajes.ler_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getLerMaterial() {
        return lerMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.ler_material
     * @param lerMaterial  the value for t_pesajes.ler_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setLerMaterial(String lerMaterial) {
        this.lerMaterial = lerMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.desc_material
     * @return  the value of t_pesajes.desc_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getDescMaterial() {
        return descMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.desc_material
     * @param descMaterial  the value for t_pesajes.desc_material
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setDescMaterial(String descMaterial) {
        this.descMaterial = descMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.kgs_bruto
     * @return  the value of t_pesajes.kgs_bruto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getKgsBruto() {
        return kgsBruto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.kgs_bruto
     * @param kgsBruto  the value for t_pesajes.kgs_bruto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setKgsBruto(String kgsBruto) {
        this.kgsBruto = kgsBruto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.kgs_neto
     * @return  the value of t_pesajes.kgs_neto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getKgsNeto() {
        return kgsNeto;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.kgs_neto
     * @param kgsNeto  the value for t_pesajes.kgs_neto
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setKgsNeto(String kgsNeto) {
        this.kgsNeto = kgsNeto;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.tara
     * @return  the value of t_pesajes.tara
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getTara() {
        return tara;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.tara
     * @param tara  the value for t_pesajes.tara
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setTara(String tara) {
        this.tara = tara;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.usu_crea
     * @return  the value of t_pesajes.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.usu_crea
     * @param usuCrea  the value for t_pesajes.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.fecha_crea
     * @return  the value of t_pesajes.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.fecha_crea
     * @param fechaCrea  the value for t_pesajes.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.usu_modifica
     * @return  the value of t_pesajes.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.usu_modifica
     * @param usuModifica  the value for t_pesajes.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.fecha_modifica
     * @return  the value of t_pesajes.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.fecha_modifica
     * @param fechaModifica  the value for t_pesajes.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.id_factura
     * @return  the value of t_pesajes.id_factura
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getIdFactura() {
        return idFactura;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.id_factura
     * @param idFactura  the value for t_pesajes.id_factura
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIdFactura(String idFactura) {
        this.idFactura = idFactura;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_pesajes.estado
     * @return  the value of t_pesajes.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_pesajes.estado
     * @param estado  the value for t_pesajes.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Constructor a partir de TPesajes
     * @param co El objeto con los datos a nutrir.
     */
    public TPesajesVista(TPesajes p) {
        DecimalFormat df = new DecimalFormat("#,##0.000");
        this.descMaterial = Utils.formatearValorString(p.getDescMaterial());
        this.destino = Utils.formatearValorString(p.getDestino());
        this.estado = p.getEstado().equals(PesajesEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(p.getFechaCrea());
        this.fechaModifica = p.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(p.getFechaModifica()) : "-";
        this.fechaPesaje = new SimpleDateFormat("dd/MM/yyyy").format(p.getFechaPesaje());
        this.id = "" + p.getId();
        this.idCliente = "" + p.getIdCliente();
        this.idDireccion = "" + p.getIdDireccion();
        this.idFactura = "" + p.getIdFactura();
        this.idMaterial = "" + p.getIdMaterial();
        this.kgsBruto = df.format(p.getKgsBruto());
        this.kgsNeto = df.format(p.getKgsNeto());
        this.lerMaterial = Utils.formatearValorString(p.getLerMaterial());
        this.numeroAlbaran = Utils.formatearValorString(p.getNumeroAlbaran());
        this.obra = Utils.formatearValorString(p.getObra());
        this.origen = Utils.formatearValorString(p.getOrigen());
        this.refMaterial = Utils.formatearValorString(p.getRefMaterial());
        this.tara = df.format(p.getTara());
        this.usuCrea = "" + p.getUsuCrea();
        this.usuModifica = "" + p.getUsuModifica();
    }
}