package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;

import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.ProductoEnum;

public class TProductosVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.id
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.descripcion
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            descripcion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.usu_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.tipo
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            tipo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.fecha_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.usu_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.fecha_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_productos.estado
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_productos
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.id
     * @return  the value of t_productos.id
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.id
     * @param id  the value for t_productos.id
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.descripcion
     * @return  the value of t_productos.descripcion
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.descripcion
     * @param descripcion  the value for t_productos.descripcion
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.usu_crea
     * @return  the value of t_productos.usu_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.usu_crea
     * @param usuCrea  the value for t_productos.usu_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.tipo
     * @return  the value of t_productos.tipo
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.tipo
     * @param tipo  the value for t_productos.tipo
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.fecha_crea
     * @return  the value of t_productos.fecha_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.fecha_crea
     * @param fechaCrea  the value for t_productos.fecha_crea
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.usu_modifica
     * @return  the value of t_productos.usu_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.usu_modifica
     * @param usuModifica  the value for t_productos.usu_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.fecha_modifica
     * @return  the value of t_productos.fecha_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.fecha_modifica
     * @param fechaModifica  the value for t_productos.fecha_modifica
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_productos.estado
     * @return  the value of t_productos.estado
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_productos.estado
     * @param estado  the value for t_productos.estado
     * @mbg.generated  Wed Mar 31 16:29:59 CEST 2021
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Método que nos realiza la copia de los campos del producto a formato {@link java.lang.String}
     * @param prod El objeto con los datos a copiar.
     */
    public void copiaDesdeProducto(TProductos prod) {
        this.descripcion = Utils.convertirIntegerStringVista(prod.getDescripcion());
        this.estado = prod.getEstado().equals(ProductoEnum.ACTIVO.getValue()) ? "Activo" : "Desactivado";
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy").format(prod.getFechaCrea());
        this.fechaModifica = prod.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy").format(prod.getFechaModifica()) : "-";
        this.id = Utils.convertirIntegerStringVista(prod.getId());
        this.tipo = prod.getTipo().equals(ProductoEnum.CALIBRE.getValue()) ? "Calibre" : "Diámetro";
        this.usuCrea = Utils.convertirIntegerStringVista(prod.getUsuCrea());
        this.usuModifica = Utils.convertirIntegerStringVista(prod.getUsuModifica());
    }
}