package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TRegistrosCambiosMateriales implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_materiales.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_materiales.cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private String cambio;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_materiales.id_material
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private Integer idMaterial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_materiales.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private Integer usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_materiales.fecha_cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private Date fechaCambio;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_registros_cambios_materiales
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_materiales.id
     * @return  the value of t_registros_cambios_materiales.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_materiales.id
     * @param id  the value for t_registros_cambios_materiales.id
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_materiales.cambio
     * @return  the value of t_registros_cambios_materiales.cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public String getCambio() {
        return cambio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_materiales.cambio
     * @param cambio  the value for t_registros_cambios_materiales.cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setCambio(String cambio) {
        this.cambio = cambio;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_materiales.id_material
     * @return  the value of t_registros_cambios_materiales.id_material
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public Integer getIdMaterial() {
        return idMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_materiales.id_material
     * @param idMaterial  the value for t_registros_cambios_materiales.id_material
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_materiales.usu_crea
     * @return  the value of t_registros_cambios_materiales.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public Integer getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_materiales.usu_crea
     * @param usuCrea  the value for t_registros_cambios_materiales.usu_crea
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setUsuCrea(Integer usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_materiales.fecha_cambio
     * @return  the value of t_registros_cambios_materiales.fecha_cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public Date getFechaCambio() {
        return fechaCambio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_materiales.fecha_cambio
     * @param fechaCambio  the value for t_registros_cambios_materiales.fecha_cambio
     * @mbg.generated  Mon May 27 18:53:23 CEST 2024
     */
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
}