package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TRegistrosCambiosControlProductoTerminadoPesConf implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.id
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.id_control_pt
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private Integer idControlPt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.id_pesaje
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private Integer idPesaje;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.fecha
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private Date fecha;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.descripcion
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private String descripcion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_registros_cambios_control_producto_terminado_pes_conf.usu_registro
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private Integer usuRegistro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_registros_cambios_control_producto_terminado_pes_conf
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.id
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id
     * @param id  the value for t_registros_cambios_control_producto_terminado_pes_conf.id
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id_control_pt
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.id_control_pt
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public Integer getIdControlPt() {
        return idControlPt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id_control_pt
     * @param idControlPt  the value for t_registros_cambios_control_producto_terminado_pes_conf.id_control_pt
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setIdControlPt(Integer idControlPt) {
        this.idControlPt = idControlPt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id_pesaje
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.id_pesaje
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public Integer getIdPesaje() {
        return idPesaje;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.id_pesaje
     * @param idPesaje  the value for t_registros_cambios_control_producto_terminado_pes_conf.id_pesaje
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setIdPesaje(Integer idPesaje) {
        this.idPesaje = idPesaje;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.fecha
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.fecha
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.fecha
     * @param fecha  the value for t_registros_cambios_control_producto_terminado_pes_conf.fecha
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.descripcion
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.descripcion
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.descripcion
     * @param descripcion  the value for t_registros_cambios_control_producto_terminado_pes_conf.descripcion
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.usu_registro
     * @return  the value of t_registros_cambios_control_producto_terminado_pes_conf.usu_registro
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public Integer getUsuRegistro() {
        return usuRegistro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_registros_cambios_control_producto_terminado_pes_conf.usu_registro
     * @param usuRegistro  the value for t_registros_cambios_control_producto_terminado_pes_conf.usu_registro
     * @mbg.generated  Fri Apr 09 18:43:18 CEST 2021
     */
    public void setUsuRegistro(Integer usuRegistro) {
        this.usuRegistro = usuRegistro;
    }
}