package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;

import com.dina.genasoft.configuration.Constants;
import com.dina.genasoft.utils.Utils;
import com.dina.genasoft.utils.enums.TransportistaEnum;

public class TTransportistasVista implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.nombre
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            nombre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.razon_social
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            razonSocial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.cif
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            cif;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            direccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.codigo_postal
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            codigoPostal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.ciudad
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            ciudad;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            provincia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            pais;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private String            estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_transportistas
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.id
     * @return  the value of t_transportistas.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.id
     * @param id  the value for t_transportistas.id
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.nombre
     * @return  the value of t_transportistas.nombre
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.nombre
     * @param nombre  the value for t_transportistas.nombre
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.razon_social
     * @return  the value of t_transportistas.razon_social
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getRazonSocial() {
        return razonSocial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.razon_social
     * @param razonSocial  the value for t_transportistas.razon_social
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.cif
     * @return  the value of t_transportistas.cif
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getCif() {
        return cif;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.cif
     * @param cif  the value for t_transportistas.cif
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setCif(String cif) {
        this.cif = cif;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.direccion
     * @return  the value of t_transportistas.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.direccion
     * @param direccion  the value for t_transportistas.direccion
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.codigo_postal
     * @return  the value of t_transportistas.codigo_postal
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getCodigoPostal() {
        return codigoPostal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.codigo_postal
     * @param codigoPostal  the value for t_transportistas.codigo_postal
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.ciudad
     * @return  the value of t_transportistas.ciudad
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.ciudad
     * @param ciudad  the value for t_transportistas.ciudad
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.provincia
     * @return  the value of t_transportistas.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.provincia
     * @param provincia  the value for t_transportistas.provincia
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.pais
     * @return  the value of t_transportistas.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.pais
     * @param pais  the value for t_transportistas.pais
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.usu_crea
     * @return  the value of t_transportistas.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.usu_crea
     * @param usuCrea  the value for t_transportistas.usu_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.fecha_crea
     * @return  the value of t_transportistas.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.fecha_crea
     * @param fechaCrea  the value for t_transportistas.fecha_crea
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaCrea(String fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.usu_modifica
     * @return  the value of t_transportistas.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.usu_modifica
     * @param usuModifica  the value for t_transportistas.usu_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.fecha_modifica
     * @return  the value of t_transportistas.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.fecha_modifica
     * @param fechaModifica  the value for t_transportistas.fecha_modifica
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setFechaModifica(String fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.estado
     * @return  the value of t_transportistas.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.estado
     * @param estado  the value for t_transportistas.estado
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Constructor a partir de TTransportistas
     * @param co El objeto con los datos a nutrir.
     */
    public TTransportistasVista(TTransportistas tr) {
        this.cif = Utils.formatearValorString(tr.getCif());
        this.direccion = Utils.formatearValorString(tr.getDireccion());
        this.codigoPostal = Utils.formatearValorString(tr.getCodigoPostal());
        this.ciudad = Utils.formatearValorString(tr.getCiudad());
        this.provincia = Utils.formatearValorString(tr.getProvincia());
        this.pais = Utils.formatearValorString(tr.getPais());
        this.estado = tr.getEstado().equals(TransportistaEnum.ACTIVO.getValue()) ? Constants.ACTIVO : Constants.DESACTIVADO;
        this.fechaCrea = new SimpleDateFormat("dd/MM/yyyy hh:mm").format(tr.getFechaCrea());
        this.fechaModifica = tr.getFechaModifica() != null ? new SimpleDateFormat("dd/MM/yyyy hh:mm").format(tr.getFechaModifica()) : "-";
        this.id = "" + tr.getId();
        this.nombre = Utils.formatearValorString(tr.getNombre());
        this.razonSocial = Utils.formatearValorString(tr.getRazonSocial());
        this.usuCrea = "" + tr.getUsuCrea();
        this.usuModifica = "" + tr.getUsuModifica();
    }
}