package com.dina.genasoft.db.entity;

import java.io.Serializable;

public class TTrace2 implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_2.intentos
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private Integer intentos;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_trace_2
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_2.intentos
     * @return  the value of t_trace_2.intentos
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public Integer getIntentos() {
        return intentos;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_2.intentos
     * @param intentos  the value for t_trace_2.intentos
     * @mbg.generated  Tue May 28 16:07:02 CEST 2024
     */
    public void setIntentos(Integer intentos) {
        this.intentos = intentos;
    }
}