package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TTransportistas implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.id
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.nombre
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String nombre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.razon_social
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String razonSocial;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.cif
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String cif;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.direccion
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String direccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.codigo_postal
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String codigoPostal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.ciudad
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String ciudad;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.provincia
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String provincia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.pais
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private String pais;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.usu_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Integer usuCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.fecha_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Date fechaCrea;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.usu_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Integer usuModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.fecha_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Date fechaModifica;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_transportistas.estado
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private Integer estado;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_transportistas
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.id
     * @return  the value of t_transportistas.id
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.id
     * @param id  the value for t_transportistas.id
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.nombre
     * @return  the value of t_transportistas.nombre
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.nombre
     * @param nombre  the value for t_transportistas.nombre
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.razon_social
     * @return  the value of t_transportistas.razon_social
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getRazonSocial() {
        return razonSocial;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.razon_social
     * @param razonSocial  the value for t_transportistas.razon_social
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.cif
     * @return  the value of t_transportistas.cif
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getCif() {
        return cif;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.cif
     * @param cif  the value for t_transportistas.cif
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setCif(String cif) {
        this.cif = cif;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.direccion
     * @return  the value of t_transportistas.direccion
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.direccion
     * @param direccion  the value for t_transportistas.direccion
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.codigo_postal
     * @return  the value of t_transportistas.codigo_postal
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getCodigoPostal() {
        return codigoPostal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.codigo_postal
     * @param codigoPostal  the value for t_transportistas.codigo_postal
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.ciudad
     * @return  the value of t_transportistas.ciudad
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.ciudad
     * @param ciudad  the value for t_transportistas.ciudad
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.provincia
     * @return  the value of t_transportistas.provincia
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.provincia
     * @param provincia  the value for t_transportistas.provincia
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.pais
     * @return  the value of t_transportistas.pais
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.pais
     * @param pais  the value for t_transportistas.pais
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.usu_crea
     * @return  the value of t_transportistas.usu_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Integer getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.usu_crea
     * @param usuCrea  the value for t_transportistas.usu_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setUsuCrea(Integer usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.fecha_crea
     * @return  the value of t_transportistas.fecha_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Date getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.fecha_crea
     * @param fechaCrea  the value for t_transportistas.fecha_crea
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.usu_modifica
     * @return  the value of t_transportistas.usu_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Integer getUsuModifica() {
        return usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.usu_modifica
     * @param usuModifica  the value for t_transportistas.usu_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setUsuModifica(Integer usuModifica) {
        this.usuModifica = usuModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.fecha_modifica
     * @return  the value of t_transportistas.fecha_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Date getFechaModifica() {
        return fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.fecha_modifica
     * @param fechaModifica  the value for t_transportistas.fecha_modifica
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_transportistas.estado
     * @return  the value of t_transportistas.estado
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_transportistas.estado
     * @param estado  the value for t_transportistas.estado
     * @mbg.generated  Wed May 29 13:39:06 CEST 2024
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    @Override
    public String toString() {
        return nombre;
    }

    public String toString2() {
        return "TTransportistas [id=" + id + ", nombre=" + nombre + ", razonSocial=" + razonSocial + ", cif=" + cif + ", direccion=" + direccion + ", codigoPostal=" + codigoPostal + ", ciudad=" + ciudad + ", provincia=" + provincia + ", pais=" + pais
                + ", usuCrea=" + usuCrea + ", fechaCrea=" + fechaCrea + ", usuModifica=" + usuModifica + ", fechaModifica=" + fechaModifica + ", estado=" + estado + "]";
    }

}