package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class TVentas2029 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.id
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.id_externo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            idExterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            pedido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.pedido_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            pedidoFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.albaran
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            albaran;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.nombre_descriptivo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            nombreDescriptivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.albaran_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            albaranFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calibre
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calibre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calibre_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calibreFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            loteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.id_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            idPale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.id_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            idPaleFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.num_bultos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           numBultos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.num_bultos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           numBultosFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.num_bultos_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           numBultosPale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.num_bultos_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           numBultosPaleFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.proveedor
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            proveedor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.proveedor_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            proveedorFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            cliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            clienteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.fecha_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Date              fechaVenta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.fecha_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Date              fechaVentaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_trazados
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsTrazados;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_netos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsNetos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_netos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsNetosFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsEnvase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.kgs_envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            kgsEnvaseFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.variedad
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            variedad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.variedad_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            variedadFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.origen
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            origen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.origen_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            origenFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calidad_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calidadCompra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calidad_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calidadCompraFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calidad_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calidadVenta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.calidad_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            calidadVentaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.referencia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            referencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.referencia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            referenciaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.albaran_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            albaranCompra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.albaran_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            albaranCompraFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.lote_mov_alm
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            loteMovAlm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.lote_mov_alm_fi
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            loteMovAlmFi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.confeccion
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            confeccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.confeccion_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            confeccionFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            envase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            envaseFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.und_consumo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            undConsumo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.und_consumo_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            undConsumoFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.linea_pedido_lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lineaPedidoLote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.linea_pedido_lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lineaPedidoLoteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.linea_pedido_lote_caja
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lineaPedidoLoteCaja;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.linea_pedido_lote_caja_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lineaPedidoLoteCajaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.familia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            familia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.familia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            familiaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.usu_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           usuCrea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.fecha_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Date              fechaCrea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.ind_nueva
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           indNueva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.unidades_tarrinas
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Double            unidadesTarrinas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cerrada
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           cerrada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.ind_automatico
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           indAutomatico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.ind_basura
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           indBasura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.ggn
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            ggn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.plantilla
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            plantilla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.plantilla_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            plantillaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.fecha_salida
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Date              fechaSalida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.fecha_salida_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Date              fechaSalidaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cod_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            codCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cod_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            codClienteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.centro_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            centroDescarga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.centro_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            centroDescargaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.dir_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            dirDescarga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.dir_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            dirDescargaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.categoria
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            categoria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.categoria_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            categoriaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.marca
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            marca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.marca_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            marcaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.unidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           unidades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.unidades_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           unidadesFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            pale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            paleFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.n_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            nPale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.n_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            nPaleFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.direccion_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            direccionCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.direccion_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            direccionClienteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cif_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            cifCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.cif_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            cifClienteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.telefono_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            telefonoCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.telefono_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            telefonoClienteFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.transportista
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            transportista;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.transportista_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            transportistaFin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.ind_error
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           indError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.num_trazabilidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private Integer           numTrazabilidades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ventas_2029.linea_pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private String            lineaPedido;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ventas_2029
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.id
     *
     * @return the value of t_ventas_2029.id
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.id
     *
     * @param id the value for t_ventas_2029.id
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.id_externo
     *
     * @return the value of t_ventas_2029.id_externo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getIdExterno() {
        return idExterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.id_externo
     *
     * @param idExterno the value for t_ventas_2029.id_externo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIdExterno(Double idExterno) {
        this.idExterno = idExterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.pedido
     *
     * @return the value of t_ventas_2029.pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPedido() {
        return pedido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.pedido
     *
     * @param pedido the value for t_ventas_2029.pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPedido(String pedido) {
        this.pedido = pedido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.pedido_fin
     *
     * @return the value of t_ventas_2029.pedido_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPedidoFin() {
        return pedidoFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.pedido_fin
     *
     * @param pedidoFin the value for t_ventas_2029.pedido_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPedidoFin(String pedidoFin) {
        this.pedidoFin = pedidoFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.albaran
     *
     * @return the value of t_ventas_2029.albaran
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getAlbaran() {
        return albaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.albaran
     *
     * @param albaran the value for t_ventas_2029.albaran
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setAlbaran(String albaran) {
        this.albaran = albaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.nombre_descriptivo
     *
     * @return the value of t_ventas_2029.nombre_descriptivo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getNombreDescriptivo() {
        return nombreDescriptivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.nombre_descriptivo
     *
     * @param nombreDescriptivo the value for t_ventas_2029.nombre_descriptivo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNombreDescriptivo(String nombreDescriptivo) {
        this.nombreDescriptivo = nombreDescriptivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.albaran_fin
     *
     * @return the value of t_ventas_2029.albaran_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getAlbaranFin() {
        return albaranFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.albaran_fin
     *
     * @param albaranFin the value for t_ventas_2029.albaran_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setAlbaranFin(String albaranFin) {
        this.albaranFin = albaranFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calibre
     *
     * @return the value of t_ventas_2029.calibre
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalibre() {
        return calibre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calibre
     *
     * @param calibre the value for t_ventas_2029.calibre
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalibre(String calibre) {
        this.calibre = calibre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calibre_fin
     *
     * @return the value of t_ventas_2029.calibre_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalibreFin() {
        return calibreFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calibre_fin
     *
     * @param calibreFin the value for t_ventas_2029.calibre_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalibreFin(String calibreFin) {
        this.calibreFin = calibreFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.lote
     *
     * @return the value of t_ventas_2029.lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLote() {
        return lote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.lote
     *
     * @param lote the value for t_ventas_2029.lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLote(String lote) {
        this.lote = lote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.lote_fin
     *
     * @return the value of t_ventas_2029.lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLoteFin() {
        return loteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.lote_fin
     *
     * @param loteFin the value for t_ventas_2029.lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLoteFin(String loteFin) {
        this.loteFin = loteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.id_pale
     *
     * @return the value of t_ventas_2029.id_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getIdPale() {
        return idPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.id_pale
     *
     * @param idPale the value for t_ventas_2029.id_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIdPale(String idPale) {
        this.idPale = idPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.id_pale_fin
     *
     * @return the value of t_ventas_2029.id_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getIdPaleFin() {
        return idPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.id_pale_fin
     *
     * @param idPaleFin the value for t_ventas_2029.id_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIdPaleFin(String idPaleFin) {
        this.idPaleFin = idPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.num_bultos
     *
     * @return the value of t_ventas_2029.num_bultos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getNumBultos() {
        return numBultos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.num_bultos
     *
     * @param numBultos the value for t_ventas_2029.num_bultos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNumBultos(Integer numBultos) {
        this.numBultos = numBultos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.num_bultos_fin
     *
     * @return the value of t_ventas_2029.num_bultos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getNumBultosFin() {
        return numBultosFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.num_bultos_fin
     *
     * @param numBultosFin the value for t_ventas_2029.num_bultos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNumBultosFin(Integer numBultosFin) {
        this.numBultosFin = numBultosFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.num_bultos_pale
     *
     * @return the value of t_ventas_2029.num_bultos_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getNumBultosPale() {
        return numBultosPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.num_bultos_pale
     *
     * @param numBultosPale the value for t_ventas_2029.num_bultos_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNumBultosPale(Integer numBultosPale) {
        this.numBultosPale = numBultosPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.num_bultos_pale_fin
     *
     * @return the value of t_ventas_2029.num_bultos_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getNumBultosPaleFin() {
        return numBultosPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.num_bultos_pale_fin
     *
     * @param numBultosPaleFin the value for t_ventas_2029.num_bultos_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNumBultosPaleFin(Integer numBultosPaleFin) {
        this.numBultosPaleFin = numBultosPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.proveedor
     *
     * @return the value of t_ventas_2029.proveedor
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getProveedor() {
        return proveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.proveedor
     *
     * @param proveedor the value for t_ventas_2029.proveedor
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.proveedor_fin
     *
     * @return the value of t_ventas_2029.proveedor_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getProveedorFin() {
        return proveedorFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.proveedor_fin
     *
     * @param proveedorFin the value for t_ventas_2029.proveedor_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setProveedorFin(String proveedorFin) {
        this.proveedorFin = proveedorFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cliente
     *
     * @return the value of t_ventas_2029.cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCliente() {
        return cliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cliente
     *
     * @param cliente the value for t_ventas_2029.cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cliente_fin
     *
     * @return the value of t_ventas_2029.cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getClienteFin() {
        return clienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cliente_fin
     *
     * @param clienteFin the value for t_ventas_2029.cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setClienteFin(String clienteFin) {
        this.clienteFin = clienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.fecha_venta
     *
     * @return the value of t_ventas_2029.fecha_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Date getFechaVenta() {
        return fechaVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.fecha_venta
     *
     * @param fechaVenta the value for t_ventas_2029.fecha_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.fecha_venta_fin
     *
     * @return the value of t_ventas_2029.fecha_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Date getFechaVentaFin() {
        return fechaVentaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.fecha_venta_fin
     *
     * @param fechaVentaFin the value for t_ventas_2029.fecha_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFechaVentaFin(Date fechaVentaFin) {
        this.fechaVentaFin = fechaVentaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs
     *
     * @return the value of t_ventas_2029.kgs
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgs() {
        return kgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs
     *
     * @param kgs the value for t_ventas_2029.kgs
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgs(Double kgs) {
        this.kgs = kgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_fin
     *
     * @return the value of t_ventas_2029.kgs_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsFin() {
        return kgsFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_fin
     *
     * @param kgsFin the value for t_ventas_2029.kgs_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsFin(Double kgsFin) {
        this.kgsFin = kgsFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_trazados
     *
     * @return the value of t_ventas_2029.kgs_trazados
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsTrazados() {
        return kgsTrazados;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_trazados
     *
     * @param kgsTrazados the value for t_ventas_2029.kgs_trazados
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsTrazados(Double kgsTrazados) {
        this.kgsTrazados = kgsTrazados;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_netos
     *
     * @return the value of t_ventas_2029.kgs_netos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsNetos() {
        return kgsNetos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_netos
     *
     * @param kgsNetos the value for t_ventas_2029.kgs_netos
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsNetos(Double kgsNetos) {
        this.kgsNetos = kgsNetos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_netos_fin
     *
     * @return the value of t_ventas_2029.kgs_netos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsNetosFin() {
        return kgsNetosFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_netos_fin
     *
     * @param kgsNetosFin the value for t_ventas_2029.kgs_netos_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsNetosFin(Double kgsNetosFin) {
        this.kgsNetosFin = kgsNetosFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_envase
     *
     * @return the value of t_ventas_2029.kgs_envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsEnvase() {
        return kgsEnvase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_envase
     *
     * @param kgsEnvase the value for t_ventas_2029.kgs_envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsEnvase(Double kgsEnvase) {
        this.kgsEnvase = kgsEnvase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.kgs_envase_fin
     *
     * @return the value of t_ventas_2029.kgs_envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getKgsEnvaseFin() {
        return kgsEnvaseFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.kgs_envase_fin
     *
     * @param kgsEnvaseFin the value for t_ventas_2029.kgs_envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setKgsEnvaseFin(Double kgsEnvaseFin) {
        this.kgsEnvaseFin = kgsEnvaseFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.variedad
     *
     * @return the value of t_ventas_2029.variedad
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getVariedad() {
        return variedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.variedad
     *
     * @param variedad the value for t_ventas_2029.variedad
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setVariedad(String variedad) {
        this.variedad = variedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.variedad_fin
     *
     * @return the value of t_ventas_2029.variedad_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getVariedadFin() {
        return variedadFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.variedad_fin
     *
     * @param variedadFin the value for t_ventas_2029.variedad_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setVariedadFin(String variedadFin) {
        this.variedadFin = variedadFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.origen
     *
     * @return the value of t_ventas_2029.origen
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.origen
     *
     * @param origen the value for t_ventas_2029.origen
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.origen_fin
     *
     * @return the value of t_ventas_2029.origen_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getOrigenFin() {
        return origenFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.origen_fin
     *
     * @param origenFin the value for t_ventas_2029.origen_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setOrigenFin(String origenFin) {
        this.origenFin = origenFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calidad_compra
     *
     * @return the value of t_ventas_2029.calidad_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalidadCompra() {
        return calidadCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calidad_compra
     *
     * @param calidadCompra the value for t_ventas_2029.calidad_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalidadCompra(String calidadCompra) {
        this.calidadCompra = calidadCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calidad_compra_fin
     *
     * @return the value of t_ventas_2029.calidad_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalidadCompraFin() {
        return calidadCompraFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calidad_compra_fin
     *
     * @param calidadCompraFin the value for t_ventas_2029.calidad_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalidadCompraFin(String calidadCompraFin) {
        this.calidadCompraFin = calidadCompraFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calidad_venta
     *
     * @return the value of t_ventas_2029.calidad_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalidadVenta() {
        return calidadVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calidad_venta
     *
     * @param calidadVenta the value for t_ventas_2029.calidad_venta
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalidadVenta(String calidadVenta) {
        this.calidadVenta = calidadVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.calidad_venta_fin
     *
     * @return the value of t_ventas_2029.calidad_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCalidadVentaFin() {
        return calidadVentaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.calidad_venta_fin
     *
     * @param calidadVentaFin the value for t_ventas_2029.calidad_venta_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCalidadVentaFin(String calidadVentaFin) {
        this.calidadVentaFin = calidadVentaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.referencia
     *
     * @return the value of t_ventas_2029.referencia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getReferencia() {
        return referencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.referencia
     *
     * @param referencia the value for t_ventas_2029.referencia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.referencia_fin
     *
     * @return the value of t_ventas_2029.referencia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getReferenciaFin() {
        return referenciaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.referencia_fin
     *
     * @param referenciaFin the value for t_ventas_2029.referencia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setReferenciaFin(String referenciaFin) {
        this.referenciaFin = referenciaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.albaran_compra
     *
     * @return the value of t_ventas_2029.albaran_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getAlbaranCompra() {
        return albaranCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.albaran_compra
     *
     * @param albaranCompra the value for t_ventas_2029.albaran_compra
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setAlbaranCompra(String albaranCompra) {
        this.albaranCompra = albaranCompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.albaran_compra_fin
     *
     * @return the value of t_ventas_2029.albaran_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getAlbaranCompraFin() {
        return albaranCompraFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.albaran_compra_fin
     *
     * @param albaranCompraFin the value for t_ventas_2029.albaran_compra_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setAlbaranCompraFin(String albaranCompraFin) {
        this.albaranCompraFin = albaranCompraFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.lote_mov_alm
     *
     * @return the value of t_ventas_2029.lote_mov_alm
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLoteMovAlm() {
        return loteMovAlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.lote_mov_alm
     *
     * @param loteMovAlm the value for t_ventas_2029.lote_mov_alm
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLoteMovAlm(String loteMovAlm) {
        this.loteMovAlm = loteMovAlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.lote_mov_alm_fi
     *
     * @return the value of t_ventas_2029.lote_mov_alm_fi
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLoteMovAlmFi() {
        return loteMovAlmFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.lote_mov_alm_fi
     *
     * @param loteMovAlmFi the value for t_ventas_2029.lote_mov_alm_fi
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLoteMovAlmFi(String loteMovAlmFi) {
        this.loteMovAlmFi = loteMovAlmFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.confeccion
     *
     * @return the value of t_ventas_2029.confeccion
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getConfeccion() {
        return confeccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.confeccion
     *
     * @param confeccion the value for t_ventas_2029.confeccion
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setConfeccion(String confeccion) {
        this.confeccion = confeccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.confeccion_fin
     *
     * @return the value of t_ventas_2029.confeccion_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getConfeccionFin() {
        return confeccionFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.confeccion_fin
     *
     * @param confeccionFin the value for t_ventas_2029.confeccion_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setConfeccionFin(String confeccionFin) {
        this.confeccionFin = confeccionFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.envase
     *
     * @return the value of t_ventas_2029.envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getEnvase() {
        return envase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.envase
     *
     * @param envase the value for t_ventas_2029.envase
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setEnvase(String envase) {
        this.envase = envase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.envase_fin
     *
     * @return the value of t_ventas_2029.envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getEnvaseFin() {
        return envaseFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.envase_fin
     *
     * @param envaseFin the value for t_ventas_2029.envase_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setEnvaseFin(String envaseFin) {
        this.envaseFin = envaseFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.und_consumo
     *
     * @return the value of t_ventas_2029.und_consumo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getUndConsumo() {
        return undConsumo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.und_consumo
     *
     * @param undConsumo the value for t_ventas_2029.und_consumo
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUndConsumo(String undConsumo) {
        this.undConsumo = undConsumo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.und_consumo_fin
     *
     * @return the value of t_ventas_2029.und_consumo_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getUndConsumoFin() {
        return undConsumoFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.und_consumo_fin
     *
     * @param undConsumoFin the value for t_ventas_2029.und_consumo_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUndConsumoFin(String undConsumoFin) {
        this.undConsumoFin = undConsumoFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.linea_pedido_lote
     *
     * @return the value of t_ventas_2029.linea_pedido_lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLineaPedidoLote() {
        return lineaPedidoLote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.linea_pedido_lote
     *
     * @param lineaPedidoLote the value for t_ventas_2029.linea_pedido_lote
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLineaPedidoLote(String lineaPedidoLote) {
        this.lineaPedidoLote = lineaPedidoLote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.linea_pedido_lote_fin
     *
     * @return the value of t_ventas_2029.linea_pedido_lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLineaPedidoLoteFin() {
        return lineaPedidoLoteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.linea_pedido_lote_fin
     *
     * @param lineaPedidoLoteFin the value for t_ventas_2029.linea_pedido_lote_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLineaPedidoLoteFin(String lineaPedidoLoteFin) {
        this.lineaPedidoLoteFin = lineaPedidoLoteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.linea_pedido_lote_caja
     *
     * @return the value of t_ventas_2029.linea_pedido_lote_caja
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLineaPedidoLoteCaja() {
        return lineaPedidoLoteCaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.linea_pedido_lote_caja
     *
     * @param lineaPedidoLoteCaja the value for t_ventas_2029.linea_pedido_lote_caja
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLineaPedidoLoteCaja(String lineaPedidoLoteCaja) {
        this.lineaPedidoLoteCaja = lineaPedidoLoteCaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.linea_pedido_lote_caja_fin
     *
     * @return the value of t_ventas_2029.linea_pedido_lote_caja_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLineaPedidoLoteCajaFin() {
        return lineaPedidoLoteCajaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.linea_pedido_lote_caja_fin
     *
     * @param lineaPedidoLoteCajaFin the value for t_ventas_2029.linea_pedido_lote_caja_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLineaPedidoLoteCajaFin(String lineaPedidoLoteCajaFin) {
        this.lineaPedidoLoteCajaFin = lineaPedidoLoteCajaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.familia
     *
     * @return the value of t_ventas_2029.familia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getFamilia() {
        return familia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.familia
     *
     * @param familia the value for t_ventas_2029.familia
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFamilia(String familia) {
        this.familia = familia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.familia_fin
     *
     * @return the value of t_ventas_2029.familia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getFamiliaFin() {
        return familiaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.familia_fin
     *
     * @param familiaFin the value for t_ventas_2029.familia_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFamiliaFin(String familiaFin) {
        this.familiaFin = familiaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.usu_crea
     *
     * @return the value of t_ventas_2029.usu_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getUsuCrea() {
        return usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.usu_crea
     *
     * @param usuCrea the value for t_ventas_2029.usu_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUsuCrea(Integer usuCrea) {
        this.usuCrea = usuCrea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.fecha_crea
     *
     * @return the value of t_ventas_2029.fecha_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Date getFechaCrea() {
        return fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.fecha_crea
     *
     * @param fechaCrea the value for t_ventas_2029.fecha_crea
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.ind_nueva
     *
     * @return the value of t_ventas_2029.ind_nueva
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getIndNueva() {
        return indNueva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.ind_nueva
     *
     * @param indNueva the value for t_ventas_2029.ind_nueva
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIndNueva(Integer indNueva) {
        this.indNueva = indNueva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.unidades_tarrinas
     *
     * @return the value of t_ventas_2029.unidades_tarrinas
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Double getUnidadesTarrinas() {
        return unidadesTarrinas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.unidades_tarrinas
     *
     * @param unidadesTarrinas the value for t_ventas_2029.unidades_tarrinas
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUnidadesTarrinas(Double unidadesTarrinas) {
        this.unidadesTarrinas = unidadesTarrinas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cerrada
     *
     * @return the value of t_ventas_2029.cerrada
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getCerrada() {
        return cerrada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cerrada
     *
     * @param cerrada the value for t_ventas_2029.cerrada
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCerrada(Integer cerrada) {
        this.cerrada = cerrada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.ind_automatico
     *
     * @return the value of t_ventas_2029.ind_automatico
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getIndAutomatico() {
        return indAutomatico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.ind_automatico
     *
     * @param indAutomatico the value for t_ventas_2029.ind_automatico
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIndAutomatico(Integer indAutomatico) {
        this.indAutomatico = indAutomatico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.ind_basura
     *
     * @return the value of t_ventas_2029.ind_basura
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getIndBasura() {
        return indBasura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.ind_basura
     *
     * @param indBasura the value for t_ventas_2029.ind_basura
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIndBasura(Integer indBasura) {
        this.indBasura = indBasura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.ggn
     *
     * @return the value of t_ventas_2029.ggn
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getGgn() {
        return ggn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.ggn
     *
     * @param ggn the value for t_ventas_2029.ggn
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setGgn(String ggn) {
        this.ggn = ggn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.plantilla
     *
     * @return the value of t_ventas_2029.plantilla
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPlantilla() {
        return plantilla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.plantilla
     *
     * @param plantilla the value for t_ventas_2029.plantilla
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPlantilla(String plantilla) {
        this.plantilla = plantilla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.plantilla_fin
     *
     * @return the value of t_ventas_2029.plantilla_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPlantillaFin() {
        return plantillaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.plantilla_fin
     *
     * @param plantillaFin the value for t_ventas_2029.plantilla_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPlantillaFin(String plantillaFin) {
        this.plantillaFin = plantillaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.fecha_salida
     *
     * @return the value of t_ventas_2029.fecha_salida
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Date getFechaSalida() {
        return fechaSalida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.fecha_salida
     *
     * @param fechaSalida the value for t_ventas_2029.fecha_salida
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.fecha_salida_fin
     *
     * @return the value of t_ventas_2029.fecha_salida_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Date getFechaSalidaFin() {
        return fechaSalidaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.fecha_salida_fin
     *
     * @param fechaSalidaFin the value for t_ventas_2029.fecha_salida_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setFechaSalidaFin(Date fechaSalidaFin) {
        this.fechaSalidaFin = fechaSalidaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cod_cliente
     *
     * @return the value of t_ventas_2029.cod_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCodCliente() {
        return codCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cod_cliente
     *
     * @param codCliente the value for t_ventas_2029.cod_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cod_cliente_fin
     *
     * @return the value of t_ventas_2029.cod_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCodClienteFin() {
        return codClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cod_cliente_fin
     *
     * @param codClienteFin the value for t_ventas_2029.cod_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCodClienteFin(String codClienteFin) {
        this.codClienteFin = codClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.centro_descarga
     *
     * @return the value of t_ventas_2029.centro_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCentroDescarga() {
        return centroDescarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.centro_descarga
     *
     * @param centroDescarga the value for t_ventas_2029.centro_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCentroDescarga(String centroDescarga) {
        this.centroDescarga = centroDescarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.centro_descarga_fin
     *
     * @return the value of t_ventas_2029.centro_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCentroDescargaFin() {
        return centroDescargaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.centro_descarga_fin
     *
     * @param centroDescargaFin the value for t_ventas_2029.centro_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCentroDescargaFin(String centroDescargaFin) {
        this.centroDescargaFin = centroDescargaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.dir_descarga
     *
     * @return the value of t_ventas_2029.dir_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getDirDescarga() {
        return dirDescarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.dir_descarga
     *
     * @param dirDescarga the value for t_ventas_2029.dir_descarga
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setDirDescarga(String dirDescarga) {
        this.dirDescarga = dirDescarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.dir_descarga_fin
     *
     * @return the value of t_ventas_2029.dir_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getDirDescargaFin() {
        return dirDescargaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.dir_descarga_fin
     *
     * @param dirDescargaFin the value for t_ventas_2029.dir_descarga_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setDirDescargaFin(String dirDescargaFin) {
        this.dirDescargaFin = dirDescargaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.categoria
     *
     * @return the value of t_ventas_2029.categoria
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.categoria
     *
     * @param categoria the value for t_ventas_2029.categoria
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.categoria_fin
     *
     * @return the value of t_ventas_2029.categoria_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCategoriaFin() {
        return categoriaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.categoria_fin
     *
     * @param categoriaFin the value for t_ventas_2029.categoria_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCategoriaFin(String categoriaFin) {
        this.categoriaFin = categoriaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.marca
     *
     * @return the value of t_ventas_2029.marca
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getMarca() {
        return marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.marca
     *
     * @param marca the value for t_ventas_2029.marca
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setMarca(String marca) {
        this.marca = marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.marca_fin
     *
     * @return the value of t_ventas_2029.marca_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getMarcaFin() {
        return marcaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.marca_fin
     *
     * @param marcaFin the value for t_ventas_2029.marca_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setMarcaFin(String marcaFin) {
        this.marcaFin = marcaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.unidades
     *
     * @return the value of t_ventas_2029.unidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getUnidades() {
        return unidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.unidades
     *
     * @param unidades the value for t_ventas_2029.unidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUnidades(Integer unidades) {
        this.unidades = unidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.unidades_fin
     *
     * @return the value of t_ventas_2029.unidades_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getUnidadesFin() {
        return unidadesFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.unidades_fin
     *
     * @param unidadesFin the value for t_ventas_2029.unidades_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setUnidadesFin(Integer unidadesFin) {
        this.unidadesFin = unidadesFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.pale
     *
     * @return the value of t_ventas_2029.pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPale() {
        return pale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.pale
     *
     * @param pale the value for t_ventas_2029.pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPale(String pale) {
        this.pale = pale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.pale_fin
     *
     * @return the value of t_ventas_2029.pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getPaleFin() {
        return paleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.pale_fin
     *
     * @param paleFin the value for t_ventas_2029.pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setPaleFin(String paleFin) {
        this.paleFin = paleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.n_pale
     *
     * @return the value of t_ventas_2029.n_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getnPale() {
        return nPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.n_pale
     *
     * @param nPale the value for t_ventas_2029.n_pale
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setnPale(String nPale) {
        this.nPale = nPale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.n_pale_fin
     *
     * @return the value of t_ventas_2029.n_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getnPaleFin() {
        return nPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.n_pale_fin
     *
     * @param nPaleFin the value for t_ventas_2029.n_pale_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setnPaleFin(String nPaleFin) {
        this.nPaleFin = nPaleFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.direccion_cliente
     *
     * @return the value of t_ventas_2029.direccion_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getDireccionCliente() {
        return direccionCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.direccion_cliente
     *
     * @param direccionCliente the value for t_ventas_2029.direccion_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.direccion_cliente_fin
     *
     * @return the value of t_ventas_2029.direccion_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getDireccionClienteFin() {
        return direccionClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.direccion_cliente_fin
     *
     * @param direccionClienteFin the value for t_ventas_2029.direccion_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setDireccionClienteFin(String direccionClienteFin) {
        this.direccionClienteFin = direccionClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cif_cliente
     *
     * @return the value of t_ventas_2029.cif_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCifCliente() {
        return cifCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cif_cliente
     *
     * @param cifCliente the value for t_ventas_2029.cif_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCifCliente(String cifCliente) {
        this.cifCliente = cifCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.cif_cliente_fin
     *
     * @return the value of t_ventas_2029.cif_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getCifClienteFin() {
        return cifClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.cif_cliente_fin
     *
     * @param cifClienteFin the value for t_ventas_2029.cif_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setCifClienteFin(String cifClienteFin) {
        this.cifClienteFin = cifClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.telefono_cliente
     *
     * @return the value of t_ventas_2029.telefono_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getTelefonoCliente() {
        return telefonoCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.telefono_cliente
     *
     * @param telefonoCliente the value for t_ventas_2029.telefono_cliente
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.telefono_cliente_fin
     *
     * @return the value of t_ventas_2029.telefono_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getTelefonoClienteFin() {
        return telefonoClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.telefono_cliente_fin
     *
     * @param telefonoClienteFin the value for t_ventas_2029.telefono_cliente_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setTelefonoClienteFin(String telefonoClienteFin) {
        this.telefonoClienteFin = telefonoClienteFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.transportista
     *
     * @return the value of t_ventas_2029.transportista
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getTransportista() {
        return transportista;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.transportista
     *
     * @param transportista the value for t_ventas_2029.transportista
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setTransportista(String transportista) {
        this.transportista = transportista;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.transportista_fin
     *
     * @return the value of t_ventas_2029.transportista_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getTransportistaFin() {
        return transportistaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.transportista_fin
     *
     * @param transportistaFin the value for t_ventas_2029.transportista_fin
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setTransportistaFin(String transportistaFin) {
        this.transportistaFin = transportistaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.ind_error
     *
     * @return the value of t_ventas_2029.ind_error
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getIndError() {
        return indError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.ind_error
     *
     * @param indError the value for t_ventas_2029.ind_error
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setIndError(Integer indError) {
        this.indError = indError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.num_trazabilidades
     *
     * @return the value of t_ventas_2029.num_trazabilidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public Integer getNumTrazabilidades() {
        return numTrazabilidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.num_trazabilidades
     *
     * @param numTrazabilidades the value for t_ventas_2029.num_trazabilidades
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setNumTrazabilidades(Integer numTrazabilidades) {
        this.numTrazabilidades = numTrazabilidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ventas_2029.linea_pedido
     *
     * @return the value of t_ventas_2029.linea_pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public String getLineaPedido() {
        return lineaPedido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ventas_2029.linea_pedido
     *
     * @param lineaPedido the value for t_ventas_2029.linea_pedido
     *
     * @mbg.generated Wed Apr 24 13:50:28 CEST 2024
     */
    public void setLineaPedido(String lineaPedido) {
        this.lineaPedido = lineaPedido;
    }

    /**
     * Constructor a partir del objecto Ventas, se setean todos los valores de la venta.
     * @param v La venta con los datos a copiar
     */
    public TVentas2029(TVentas v) {
        this.albaran = v.getAlbaran();
        this.albaranCompra = v.getAlbaranCompra();
        this.albaranCompraFin = v.getAlbaranCompraFin();
        this.albaranFin = v.getAlbaranFin();
        this.calibre = v.getCalibre();
        this.calibreFin = v.getCalibreFin();
        this.calidadCompra = v.getCalidadCompra();
        this.calidadCompraFin = v.getCalidadCompraFin();
        this.calidadVenta = v.getCalidadVenta();
        this.calidadVentaFin = v.getCalidadVentaFin();
        this.categoria = v.getCategoria();
        this.categoriaFin = v.getCategoriaFin();
        this.centroDescarga = v.getCentroDescarga();
        this.centroDescargaFin = v.getCentroDescargaFin();
        this.cerrada = v.getCerrada();
        this.cifCliente = v.getCifCliente();
        this.cifClienteFin = v.getCifClienteFin();
        this.cliente = v.getCliente();
        this.clienteFin = v.getClienteFin();
        this.codCliente = v.getCodCliente();
        this.codClienteFin = v.getCodClienteFin();
        this.confeccion = v.getConfeccion();
        this.confeccionFin = v.getConfeccionFin();
        this.dirDescarga = v.getDirDescarga();
        this.dirDescargaFin = v.getDirDescargaFin();
        this.direccionCliente = v.getDireccionCliente();
        this.direccionClienteFin = v.getDireccionClienteFin();
        this.envase = v.getEnvase();
        this.envaseFin = v.getEnvaseFin();
        this.familia = v.getFamilia();
        this.familiaFin = v.getFamiliaFin();
        this.fechaCrea = v.getFechaCrea();
        this.fechaSalida = v.getFechaSalida();
        this.fechaSalidaFin = v.getFechaSalidaFin();
        this.fechaVenta = v.getFechaVenta();
        this.fechaVentaFin = v.getFechaVentaFin();
        this.ggn = v.getGgn();
        this.id = v.getId();
        this.idExterno = v.getIdExterno();
        this.idPale = v.getIdPale();
        this.idPaleFin = v.getIdPaleFin();
        this.indAutomatico = v.getIndAutomatico();
        this.indBasura = v.getIndBasura();
        this.indError = v.getIndError();
        this.indNueva = v.getIndNueva();
        this.kgs = v.getKgs();
        this.kgsEnvase = v.getKgsEnvase();
        this.kgsEnvaseFin = v.getKgsEnvaseFin();
        this.kgsFin = v.getKgsFin();
        this.kgsNetos = v.getKgsNetos();
        this.kgsNetosFin = v.getKgsNetosFin();
        this.kgsTrazados = v.getKgsTrazados();
        this.lineaPedido = v.getLineaPedido();
        this.lineaPedidoLote = v.getLineaPedidoLote();
        this.lineaPedidoLoteCaja = v.getLineaPedidoLoteCaja();
        this.lineaPedidoLoteCajaFin = v.getLineaPedidoLoteCajaFin();
        this.lineaPedidoLoteFin = v.getLineaPedidoLoteFin();
        this.lote = v.getLote();
        this.loteFin = v.getLoteFin();
        this.loteMovAlm = v.getLoteMovAlm();
        this.loteMovAlmFi = v.getLoteMovAlmFi();
        this.marca = v.getMarca();
        this.marcaFin = v.getMarcaFin();
        this.nombreDescriptivo = v.getNombreDescriptivo();
        this.nPale = v.getnPale();
        this.nPaleFin = v.getnPaleFin();
        this.numBultos = v.getNumBultos();
        this.numBultosFin = v.getNumBultosFin();
        this.numBultosPale = v.getNumBultosPale();
        this.numBultosPaleFin = v.getNumBultosPaleFin();
        this.numTrazabilidades = v.getNumTrazabilidades();
        this.origen = v.getOrigen();
        this.origenFin = v.getOrigenFin();
        this.pale = v.getPale();
        this.paleFin = v.getPaleFin();
        this.pedido = v.getPedido();
        this.pedidoFin = v.getPedidoFin();
        this.plantilla = v.getPlantilla();
        this.plantillaFin = v.getPlantillaFin();
        this.proveedor = v.getProveedor();
        this.proveedorFin = v.getProveedorFin();
        this.referencia = v.getReferencia();
        this.referenciaFin = v.getReferenciaFin();
        this.telefonoCliente = v.getTelefonoCliente();
        this.telefonoClienteFin = v.getTelefonoClienteFin();
        this.transportista = v.getTransportista();
        this.transportistaFin = v.getTransportistaFin();
        this.undConsumo = v.getUndConsumo();
        this.undConsumoFin = v.getUndConsumoFin();
        this.unidades = v.getUnidades();
        this.unidadesFin = v.getUnidadesFin();
        this.unidadesTarrinas = v.getUnidadesTarrinas();
        this.usuCrea = v.getUsuCrea();
        this.variedad = v.getVariedad();
        this.variedadFin = v.getVariedadFin();
    }
}