package com.dina.genasoft.db.entity;

import java.io.Serializable;
import java.util.Date;

public class VarArt implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Integer sqlId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date sqlModTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String ref;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private String nameAbr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long altUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date altTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long modUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date modTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long offUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Date offTim;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Short off;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column var_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private Long artPla;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table var_art
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.sql_id
     * @return  the value of var_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Integer getSqlId() {
        return sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.sql_id
     * @param sqlId  the value for var_art.sql_id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlId(Integer sqlId) {
        this.sqlId = sqlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.sql_mod_tim
     * @return  the value of var_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getSqlModTim() {
        return sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.sql_mod_tim
     * @param sqlModTim  the value for var_art.sql_mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setSqlModTim(Date sqlModTim) {
        this.sqlModTim = sqlModTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.id
     * @return  the value of var_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.id
     * @param id  the value for var_art.id
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.ref
     * @return  the value of var_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.ref
     * @param ref  the value for var_art.ref
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.name
     * @return  the value of var_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.name
     * @param name  the value for var_art.name
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.name_abr
     * @return  the value of var_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public String getNameAbr() {
        return nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.name_abr
     * @param nameAbr  the value for var_art.name_abr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setNameAbr(String nameAbr) {
        this.nameAbr = nameAbr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.alt_usr
     * @return  the value of var_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getAltUsr() {
        return altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.alt_usr
     * @param altUsr  the value for var_art.alt_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltUsr(Long altUsr) {
        this.altUsr = altUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.alt_tim
     * @return  the value of var_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getAltTim() {
        return altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.alt_tim
     * @param altTim  the value for var_art.alt_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setAltTim(Date altTim) {
        this.altTim = altTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.mod_usr
     * @return  the value of var_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getModUsr() {
        return modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.mod_usr
     * @param modUsr  the value for var_art.mod_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModUsr(Long modUsr) {
        this.modUsr = modUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.mod_tim
     * @return  the value of var_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getModTim() {
        return modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.mod_tim
     * @param modTim  the value for var_art.mod_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setModTim(Date modTim) {
        this.modTim = modTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.off_usr
     * @return  the value of var_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getOffUsr() {
        return offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.off_usr
     * @param offUsr  the value for var_art.off_usr
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffUsr(Long offUsr) {
        this.offUsr = offUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.off_tim
     * @return  the value of var_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Date getOffTim() {
        return offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.off_tim
     * @param offTim  the value for var_art.off_tim
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOffTim(Date offTim) {
        this.offTim = offTim;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.off
     * @return  the value of var_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Short getOff() {
        return off;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.off
     * @param off  the value for var_art.off
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setOff(Short off) {
        this.off = off;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column var_art.art_pla
     * @return  the value of var_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public Long getArtPla() {
        return artPla;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column var_art.art_pla
     * @param artPla  the value for var_art.art_pla
     * @mbg.generated  Mon Jul 18 11:27:46 CEST 2022
     */
    public void setArtPla(Long artPla) {
        this.artPla = artPla;
    }
}